<?php
// @codingStandardsIgnoreFile
?>
<?php if ($this->isEnabled()) : ?>
    <?php $helper = $this->helper('WeltPixel\GA4\Helper\Data'); ?>
    <?php
    $products = $this->getProducts();
    $this->setDataLayerOption('event', 'view_cart');
    $this->setDataLayerOption('cart_total', floatval(number_format($this->getCartTotal(), 2, '.', '')));
    $this->setDataLayerOption('total', floatval(number_format($this->getCartTotal(), 2, '.', '')));
    $this->setEcommerceData('items', $products);
    $this->setEcommerceData('value', floatval(number_format($this->getCartTotal(), 2, '.', '')));
    $this->setEcommerceData('currency', $this->getCurrencyCode());
    ?>


        <?php
        $crosselProductsCollection = $this->getCrosselProductCollection();
        $productImpressions = [];

        if (count($crosselProductsCollection)) :
            $i = 1;
            foreach ($crosselProductsCollection as $_product) :
                $crosselProduct = [];
                $crosselProduct['item_name'] = html_entity_decode($_product->getName() ?? '');
                $crosselProduct['affiliation'] = $helper->getAffiliationName();
                $crosselProduct['item_id'] = $helper->getGtmProductId($_product);
                $crosselProduct['price'] = floatval(number_format($_product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', ''));
                if ($helper->isBrandEnabled()) :
                    $crosselProduct['item_brand'] = $helper->getGtmBrand($_product);
                endif;
                $ga4Categories = $helper->getGA4CategoriesFromCategoryIds($_product->getCategoryIds());
                $crosselProduct = array_merge($crosselProduct, $ga4Categories);
                $crosselProduct['item_list_name'] = __('Crossel Products');
                $crosselProduct['item_list_id'] = __('crossel_products');
                $crosselProduct['index'] = $i;
                $productImpressions[] = $crosselProduct;
                $i++;
            endforeach;
        endif;

        if (count($productImpressions)) :
            $this->setImpressionData([
                'items' => $productImpressions,
                'item_list_id' =>  'crossel_products',
                'item_list_name' =>  __('Crossel Products')
            ]);
        endif;

        if ($helper->isAdWordsRemarketingEnabled()):
            $remarketingData = [];
            $remarketingData['ecomm_pagetype'] = \WeltPixel\GA4\Model\Api\Remarketing::ECOMM_PAGETYPE_CART;
            $remarketingData['ecomm_prodid'] = $this->getProductIds();
            $remarketingData['ecomm_totalvalue'] = floatval(number_format($this->getCartTotal(), 2, '.', ''));
            $this->setDataLayerOption('google_tag_params', $remarketingData);
        endif;

        ?>
<?php endif; ?>
