<?php
// @codingStandardsIgnoreFile
?>
<?php if($this->isEnabled()) : ?>
    <?php $helper = $this->helper('WeltPixel\GA4\Helper\Data'); ?>
    <?php $products = $this->getProducts(); ?>

    <?php
    $this->setDataLayerOption('event', 'begin_checkout');
    $this->setDataLayerOption('cart_total', floatval(number_format($this->getCartTotal(), 2, '.', '')));
    $this->setEcommerceData('items', $products);
    $this->setEcommerceData('currency', $this->getCurrencyCode());
    $this->setEcommerceData('value', floatval(number_format($this->getCartTotal(), 2, '.', '')));
    if ($this->getCouponCode()) :
        $this->setEcommerceData('coupon', $this->getCouponCode());
    endif;
    ?>
<?php endif; ?>
