<?php
// @codingStandardsIgnoreFile
?>
<?php if($this->isEnabled()) : ?>
    <?php

    $helper = $this->helper('WeltPixel\GA4\Helper\Data');
    $order = $this->getOrder();

    $checkoutPaymentData = $helper->getGA4CheckoutPaymentData();

    if ($checkoutPaymentData && is_array($checkoutPaymentData)) {
        $this->setCustomDataLayerData($checkoutPaymentData[0]);
        $helper->invalidateGA4CheckoutPaymentData();
    }


    if ($this->isFreeOrderTrackingAllowedForGoogleAnalytics()) :
        $products = $this->getProducts();

        $this->setDataLayerOption('event', 'purchase');
        $this->setEcommerceData('transaction_id', $order->getIncrementId());
        $this->setEcommerceData('value', floatval(number_format($this->getOrderTotal(), 2, '.', '')));
        if ($order->getCouponCode()) :
            $this->setEcommerceData('coupon', (string)$order->getCouponCode());
        endif;
        $this->setEcommerceData('tax', floatval(number_format($order->getTaxAmount(), 2, '.', '')));
        $this->setEcommerceData('shipping', floatval(number_format($order->getShippingAmount(), 2, '.', '')));
        $this->setEcommerceData('currency', $this->getCurrencyCode());
        $this->setEcommerceData('total_order_count', $this->getTotalOrderCount());
        $this->setEcommerceData('total_lifetime_value', floatval(number_format($this->getTotalLifetimeValue(), 2, '.', '')));
        $this->setEcommerceData('items', $products);
    endif;

    if ($helper->isAdWordConversionTrackingEnabled() && $this->isFreeOrderAllowedForAdwordsConversionTracking()) :
        $this->setDataLayerOption(\WeltPixel\GA4\Model\Api\ConversionTracking::FIELD_CONVERSION_TRACKING_CONVERSION_VALUE, $this->getOrderTotal());
        $this->setDataLayerOption(\WeltPixel\GA4\Model\Api\ConversionTracking::FIELD_CONVERSION_TRACKING_ORDER_ID, $order->getIncrementId());
    endif;

    if ($helper->isAdWordsRemarketingEnabled() && $this->isFreeOrderAllowedForAdwordsRemarketing()):
        $remarketingData = [];
        $remarketingData['ecomm_pagetype'] = \WeltPixel\GA4\Model\Api\Remarketing::ECOMM_PAGETYPE_PURCHASE;
        $remarketingData['ecomm_prodid'] = $this->getProductIds();
        $remarketingData['ecomm_totalvalue'] = floatval(number_format($this->getOrderTotal(), 2, '.', ''));
        $this->setDataLayerOption('google_tag_params', $remarketingData);
    endif;

    ?>
<?php endif; ?>
