<?php
/**
 * Provide an admin area view for the Slider Modal Options
 *
 * This file is used to markup the admin-facing aspects of the plugin.
 * @author    ThemePunch <info@themepunch.com>
 * @link      https://www.themepunch.com/
 * @copyright 2022 ThemePunch
 */

use \Nwdthemes\Revslider\Model\FrameworkAdapter as FA;

?>

<!--QUICK GUIDE MODAL-->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_colorskins">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_colorskins" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">format_paint</i><span class="rbm_title"><?php echo __('Global Color Skin');?></span><i class="rbm_close material-icons">close</i></div>
				<div class="rbm_content">
					<div class="modal_fields_title" style="width:170px;margin-right:10px;"><?php echo __('SKIN TITLE');?></div><div class="modal_fields_title"><?php echo __('SKIN COLOR');?></div>
					<div id="module_color_skins"></div>
					<div class="div20"></div>
					<div id="add_skin_color" class="basic_action_button layerinput autosize rightbutton"><i class="material-icons">color_lens</i><?php echo __('Add Skin');?></div><div class="tp-clearfix"></div>
					<div class="div40"></div>
					<div class="global_sas_wrap">
                        <label_a style="max-width:none; width:auto;"><?php echo __('Show this Modal on Editor launch');?></label_a><input type="checkbox" id="sr_show_glob_skins" class="sliderinput easyinit" data-r="skins.colorsAtStart">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!--QUICK GUIDE MODAL-->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_quickguide">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_quickguide" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">new_releases</i><span class="rbm_title"><?php echo __('Module Creation Guide');?></span><i class="rbm_close material-icons">close</i></div>
				<div class="rbm_content">
					<!-- PAGE 0 -->
					<div id="mcg_page_0"  class="mcg_page mcg_selected">
						<div class="dcenter">
							<div class="div30"></div>
							<div class="mcg_page_title"><?php echo __('Welcome to Slider Revolution 6');?></div>
							<div class="mcg_page_subtitle"><?php echo __('This Guide will help you with the basic configuration *<br>of your Slider Revolution 6 Module.');?></div>
							<div class="div100"></div>
							<bluebutton class="normal mcg_next_page"><?php echo __('Start Guide');?></bluebutton>
							<div class="div10"></div>
							<graybutton class="normal mcg_quit_page"><?php echo __('Quit Guide');?></graybutton>
						</div>
						<div class="mcg_page_footer">
							<div id="mcg_page_0_blurredbox"></div>
							<div class="mcg_footer_content">
								<grayiconbox><i class="material-icons">help_outline</i></grayiconbox>
								<blueiconbox class="blueiconongray"><i class="material-icons">help_outline</i></blueiconbox>
								<div class="mcg_fotter_text"><?php echo __('* All settings adjusted by the guide can be changed later.<br>Click the <strong>Help Icon</strong> to find options & documentation');?></div>
							</div>
						</div>
					</div>

					<!-- PAGE 1 -->
					<div id="mcg_page_1"  class="mcg_page">
						<div class="dcenter">
							<div class="div30"></div>
							<div class="mcg_page_title"><?php echo __('What type of module would you like to create?');?></div>
							<div class="div35"></div>
						</div>
						<div class="mcg_option_third_wraps">
							<div class="st_slider mcg_guide_optionwrap mcg_option_third">
                                <input data-unavailable=".standardunavailable" data-available=".standardavailable" data-disablehack=".standarddisable" data-enable=".standardenable" data-select=".st_slider" data-unselect=".st_scene, .st_carousel" data-r="type" data-evt="updatesliderlayout"  data-evtparam="slidertype" type="radio" value="standard" id="slidertype_guide_standard" name="slidertype_guide" class="sliderinput easyinit" data-show="" data-hide="">
								<mcg_guide_image class="guide_slider"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Slider');?></div>
								<div class="mcg_o_descp"><?php echo __('A Slider consists of multiple Slides.<br>Each Slide has its own content and can be<br>navigated to with various optional<br>navigation elements.');?></div>
							</div>
							<div class="st_scene mcg_guide_optionwrap mcg_option_third">
                                <input data-unavailable=".sceneunavailable" data-available=".sceneavailable" data-disablehack=".herodisable" data-enable=".heroenable" data-select=".st_scene" data-unselect=".st_slider, .st_carousel" data-r="type" data-evt="updatesliderlayout" data-evtparam="slidertype" type="radio" value="hero" name="slidertype_guide" class="sliderinput" data-show="" data-hide="">
								<mcg_guide_image class="guide_scene"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Scene');?></div>
								<div class="mcg_o_descp"><?php echo __('A Scene is essentially a Slider with a single<br>Slide and no navigation elements.<br>Best used for content modules that require<br>no additional depth.');?></div>
							</div>
							<div class="st_carousel mcg_guide_optionwrap mcg_option_third last">
                                <input data-unavailable=".carouselunavailable" data-available=".carouselavailable" data-disablehack=".carouseldisable" data-enable=".carouselenable" data-select=".st_carousel" data-unselect=".st_slider, .st_scene" data-r="type" data-evt="updatesliderlayout"  data-evtparam="slidertype" type="radio" value="carousel" id="slidertype_guide_carousel"  name="slidertype_guide" class="sliderinput easyinit" data-show="" data-hide="">
								<mcg_guide_image class="guide_carousel"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Carousel');?></div>
								<div class="mcg_o_descp"><?php echo __('A Carousel is a Slider with multiple Slides<br>visible at the same time.<br>There are lots of options to customize the Carousel.');?></div>
							</div>
						</div>
						<div class="mcg_footer_btns_right"><graybutton class="minimal mcg_prev_page"><?php echo __('Previous Step');?></graybutton></div>
						<div class="mcg_footer_btns">
							<div class="mcg_page_minititle"><?php echo __('Module Type');?></div>
							<div class="mcg_page_pagination">1/3</div>
							<bluebutton class="minimal mcg_next_page"><?php echo __('Next Step');?></bluebutton>
						</div>
					</div>

					<!-- PAGE 2 -->
					<div id="mcg_page_2"  class="mcg_page">
						<div class="dcenter">
							<div class="div30"></div>
							<div class="mcg_page_title"><?php echo __('What size should the module have?');?></div>
							<div class="div35"></div>
						</div>
						<div class="mcg_option_third_wraps">
							<div class="sl_auto mcg_guide_optionwrap mcg_option_third">
                                <input data-select=".sl_auto" data-unselect=".sl_fullwidth, .sl_fullscreen" data-r="layouttype" data-evt="updatesliderlayout" type="radio" value="auto" id="sliderlayouttype_guide_auto" name="sliderlayouttype_guide" class="sliderinput easyinit" data-show="#sr_size_minheight" data-hide=".sliderminheights,.decreaseheights">
								<mcg_guide_image class="guide_auto"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Auto');?></div>
								<div class="mcg_o_descp"><?php echo __('The module dimensions will automatically<br>adjust to the surrounding container width,<br>keeping its aspect ratio.');?></div>
							</div>
							<div class="sl_fullwidth mcg_guide_optionwrap mcg_option_third">
                                <input data-select=".sl_fullwidth" data-unselect=".sl_auto, .sl_fullscreen" data-r="layouttype" data-evt="updatesliderlayout" type="radio" value="fullwidth" id="sliderlayouttype_guide_fullwidth" name="sliderlayouttype_guide" class="sliderinput easyinit" data-show="#sr_size_minheight" data-hide=".sliderminheights,.decreaseheights">
								<mcg_guide_image class="guide_fullwidth"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Full-Width');?></div>
								<div class="mcg_o_descp"><?php echo __('The module will always span across the<br>full-width of the web-page. The height can<br>be flexible depending on other settings.');?></div>
							</div>
							<div class="sl_fullscreen mcg_guide_optionwrap mcg_option_third last">
                                <input data-select=".sl_fullscreen" data-unselect=".sl_auto, .sl_fullwidth" data-r="layouttype" data-evt="updatesliderlayout" type="radio" value="fullscreen" id="sliderlayouttype_guide_fullscreen" name="sliderlayouttype_guide" class="sliderinput easyinit" data-show="#sr_size_minheight_fs, .decreaseheights" data-hide=".sliderminheights">
								<mcg_guide_image class="guide_fullscreen"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Full-Screen');?></div>
								<div class="mcg_o_descp"><?php echo __('The module will always fit the full area<br>within the web-page.');?></div>
							</div>
						</div>
						<div class="mcg_footer_btns_right"><graybutton class="minimal mcg_prev_page"><?php echo __('Previous Step');?></graybutton></div>
						<div class="mcg_footer_btns">
							<div class="mcg_page_minititle"><?php echo __('Module Dimensions');?></div>
							<div class="mcg_page_pagination">2/3</div>
							<bluebutton class="minimal mcg_next_page"><?php echo __('Next Step');?></bluebutton>
						</div>
					</div>

					<!-- PAGE 3 -->
					<div id="mcg_page_3"  class="mcg_page">
						<div class="dcenter">
							<div class="div30"></div>
							<div class="mcg_page_title"><?php echo __('How would you like your content to resize?');?></div>
							<div class="div35"></div>
						</div>
						<div class="mcg_option_third_wraps">
							<div id="guide_classic" class="guide_combi_resize  mcg_guide_optionwrap mcg_option_third">
								<mcg_guide_image class="guide_autoresponsive"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Classic, Linear Resizing');?></div>
								<div class="mcg_o_descp"><?php echo __('Layers will resize in a linear fashion, as the module size changes. You only need to configure one screen size.');?></div>
							</div>
							<div id="guide_intelligent" class="guide_combi_resize mcg_guide_optionwrap mcg_option_third">
								<mcg_guide_image class="guide_intelligent"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Intelligent Inheriting');?></div>
								<div class="mcg_o_descp"><?php echo __('Four custom device sizes are activated and a layers size / position is automatically calculated from its desktop device size. You can make individual adjustments to layers in all device sizes.');?></div>
							</div>
							<div id="guide_manual" class="guide_combi_resize mcg_guide_optionwrap mcg_option_third last">
								<mcg_guide_image class="guide_manual"></mcg_guide_image>
								<div class="mcg_o_title"><?php echo __('Manual Custom Sizes');?></div>
								<div class="mcg_o_descp"><?php echo __('Four custom device sizes are activated and layers need to be manually adjusted to their respective device sizes.');?></div>
							</div>
						</div>
						<div class="mcg_footer_btns_right"><graybutton class="minimal mcg_prev_page"><?php echo __('Previous Step');?></graybutton></div>
						<div class="mcg_footer_btns">
							<div class="mcg_page_minititle"><?php echo __('Responisvity');?></div>
							<div class="mcg_page_pagination">3/3</div>
							<bluebutton class="minimal mcg_quit_page"><?php echo __('Go to Editor');?></bluebutton>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</div><!-- END OF QUICK GUIDE MODAL -->


<!--LAYER IMPORT/EXPORT MODAL-->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_layerimport">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_layerimport" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">import_export</i><span class="rbm_title"><?php echo __('Layer Import');?></span><i class="rbm_close material-icons">close</i></div>
				<div class="rbm_content">
					<!-- THE LEFT SIDE OF THE AWESOME MODAL WINDOW -->
					<div id="rbm_layerimport_list">
					</div>
					<div id="rbm_layerimport_buttonwrap">
						<div id="layers_import_feedback"></div>
						<div id="layers_import_from_slides_button" class="basic_action_button autosize rightbutton layerinput"><i class="material-icons">import_export</i><?php echo __('Import Selected Layers');?></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!-- END OF LAYER IMPORT/EXPORT MODAL -->


<!-- NAVIGATION EDITOR -->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_navigation_editor">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_navigation_editor" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">games</i><span class="rbm_title"><?php echo __('Navigation Editor');?></span><i class="rbm_close material-icons">close</i></div>
				<div class="rbm_content">
					<div id="save_naveditor"><i class="material-icons">save</i><?php echo __('Save Navigation');?></div>
					<div id="rs_ne_left_wrap">
						<div id="rs_ne_selector_arrows" class="rs_ne_selector selected" data-type="arrows"><i class="material-icons">swap_horiz</i><?php echo __('Arrows');?></div><!--
						--><div id="rs_ne_selector_bullets" class="rs_ne_selector" data-type="bullets"><i class="material-icons">more_horiz</i><?php echo __('Bullets');?></div><!--
						--><div id="rs_ne_selector_tabs" class="rs_ne_selector" data-type="tabs"><i class="material-icons">view_column</i><?php echo __('Tabs');?></div><!--
						--><div id="rs_ne_selector_thumbs" class="rs_ne_selector" data-type="thumbs"><i class="material-icons">filter_frames</i><?php echo __('Thumbs');?></div>
						<div id="rs_ne_navlist_wrap">
							<div id="rs_ne_navlist">
								<div class="rs_ne_navlist_header"><?php echo __('Factory Skins');?></div>
								<div class="rs_ne_list_wrapper"><div id="rs_ne_factory_list"></div></div>
								<div class="rs_ne_navlist_header"><?php echo __('Custom');?></div>
								<div class="rs_ne_list_wrapper"><div id="rs_ne_custom_list"></div></div>
							</div>
							<div class="rs_ne_add_new_wrap"><div id="rs_ne_new_custom_nav" class="basic_action_button fullbutton"><i class="material-icons">add</i><?php echo __('Add New Navigation ');?></div></div>
						</div>
					</div>

					<div id="rs_ne_right_wrap">
						<div id="rs_ne_preview_wrap">
								<!-- ARROWS -->
								<div id="rs_ne_arrows">
									<div id="rs_ne_tp-rightarrow" class="tp-rightarrow tparrows"></div>
									<div id="rs_ne_tp-leftarrow" class="tp-leftarrow tparrows"></div>
								</div>

								<!-- BULLETS -->
								<div id="rs_ne_bullets" class="tp-bullets">
								</div>

								<!-- TABS -->
								<div id="rs_ne_tabs" class="tp-tabs">
									<div id="rs_ne_tabs-mask" class="tp-tabs-mask">
										<div id="rs_ne_tabs-inner-wrapper" class="tp-tabs-inner-wrapper"></div>
									</div>
								</div>

								<!-- NAVIGATION THUMBS -->
								<div id="rs_ne_thumbs" class="tp-thumbs">
									<div id="rs_ne_thumbs-mask" class="tp-thumbs-mask">
										<div id="rs_ne_thumbs-inner-wrapper" class="tp-thumbs-inner-wrapper"></div>
									</div>
								</div>
						</div>
						<div id="rs_ne_ce_wrap">
							<div id="rs_ne_settings">
								<label_a style="width:auto"><?php echo __('Class');?></label_a><input type="text" id="rs_ne_nav_classname"/>
								<label_icon class="ui_width" style="margin-left:15px;"></label_icon><input type="text" class="basicinput callEvent" data-evt="rsdimgapchange" data-evtparam="width" id="rs_ne_nav_width"/>
								<label_icon class="ui_height" style="margin-left:5px;"></label_icon><input type="text" class="basicinput callEvent" data-evt="rsdimgapchange" data-evtparam="height" id="rs_ne_nav_height"/>
								<label_icon class="ui_gap" style="margin-left:33px;"></label_icon><input type="text" value="5" class="basicinput callEvent" data-evt="rsdimgapchange" data-evtparam="space" id="rs_ne_nav_space"/>
								<div style="margin-left:11px" id="rs_ne_horizontaltest" data-evt="setrsnavtohorizontal" class="eventcaller basic_action_button onlyicon selected"><i class="material-icons">more_horiz</i></div><div id="rs_ne_verticaltest" data-evt="setrsnavtovertical" class="eventcaller basic_action_button onlyicon"><i class="material-icons">more_vert</i></div>
								<select style="display:none !important" id="rs_nav_test_position" data-unselect=".rs_nav_test_position_selector" data-select="#rs_nav_test_position_*val*" data-evt="setrsnavposition" data-show=".rs_nav_test_pos_*val*" data-hide=".rs_nav_test_pos" class="basicinput callEvent"><option value="left center"><?php echo __('left center');?></option><option value="left bottom"><?php echo __('left bottom');?></option><option value="left top"><?php echo __('left top');?></option><option value="center top"><?php echo __('center top');?></option><option value="center center"><?php echo __('center center');?></option><option selected value="center bottom"><?php echo __('center bottom');?></option><option value="right top"><?php echo __('right top');?></option><option value="right center"><?php echo __('right center');?></option><option value="right bottom"><?php echo __('right bottom');?></option></select>
								<div class="bg_alignselector_wrap">
									<div class="bg_align_row">
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector" data-select="#rs_nav_test_position" data-val="left top" id="rs_nav_test_position_left-top"></div>
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector" data-select="#rs_nav_test_position" data-val="center top" id="rs_nav_test_position_center-top"></div>
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector" data-select="#rs_nav_test_position" data-val="right top" id="rs_nav_test_position_right-top"></div>
									</div>
									<div class="bg_align_row">
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector" data-select="#rs_nav_test_position" data-val="left center" id="rs_nav_test_position_left-center"></div>
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector" data-select="#rs_nav_test_position" data-val="center center" id="rs_nav_test_position_center-center"></div>
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector" data-select="#rs_nav_test_position" data-val="right center" id="rs_nav_test_position_right-center"></div>
									</div>
									<div class="bg_align_row">
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector" data-select="#rs_nav_test_position" data-val="left bottom" id="rs_nav_test_position_left-bottom"></div>
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector selected" data-select="#rs_nav_test_position" data-val="center bottom" id="rs_nav_test_position_center-bottom"></div>
										<div class="triggerselect rs_nav_test_position_selector bg_alignselector" data-select="#rs_nav_test_position" data-val="right bottom" id="rs_nav_test_position_right-bottom"></div>
									</div>
								</div>

							</div>
							<div id="rs_ne_markup_css_button_wrap"><div id="rs_ne_mcss_thecsseditor" data-mode="css" data-show="#rs_ne_css_meta" data-hide="#rs_ne_markup_meta" class="rs_ne_markup_css_button rsnmcb_right"><?php echo __('CSS');?></div><div data-mode="markup" data-show="#rs_ne_markup_meta" data-hide="#rs_ne_css_meta" class="rs_ne_markup_css_button rsnmcb_left selected"><?php echo __('Markup');?></div></div>
							<div id="rs_nav_css_js_area">
							</div>
						</div>
						<div id="rs_ne_helper_wrap">
							<div id="rs_ne_markup_meta">
								<div class="rs_ne_header"><?php echo __('Markup Meta');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{title}}"><?php echo __('Slide Title');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{description}}"><?php echo __('Slide Description');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param1}}"><?php echo __('Parameter 1');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param2}}"><?php echo __('Parameter 2');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param3}}"><?php echo __('Parameter 3');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param4}}"><?php echo __('Parameter 4');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param5}}"><?php echo __('Parameter 5');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param6}}"><?php echo __('Parameter 6');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param7}}"><?php echo __('Parameter 7');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param8}}"><?php echo __('Parameter 8');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param9}}"><?php echo __('Parameter 9');?></div>
								<div class="rs_ne_markup_meta_btn" data-insert="{{param10}}"><?php echo __('Parameter 10');?></div>
							</div>
							<div id="rs_ne_css_meta">
								<div id="rs_ne_cssmeta_values">
									<div class="rs_ne_header"><?php echo __('Meta Values');?></div>
									<div id="rs_ne_meta_values_inner"></div>
									<div class="rs_ne_add_new_wrap" style="padding-left:0px; padding-right:30px"><div id="add_new_placeholder" class="basic_action_button fullbutton"><i class="material-icons">add</i><?php echo __('Add New Meta');?></div></div>
								</div>
								<div id="rs_ne_cssmeta_config">
									<div class="rs_ne_header"><?php echo __('Meta Config');?></div>
									<label_a><?php echo __('Type');?></label_a><select id="rs_ne_meta_type" data-show="#rs_ne_def_meta_*val*_val_wrap" data-hide=".rs_ne_def_meta_wrap" class="tos2 nosearchbox basicinput"><option value="color"><?php echo __('Color');?></option></option><option selected value="custom"><?php echo __('Custom');?></option><option value="font-family"><?php echo __('Font Family');?></option><option value="icon"><?php echo __('Icon');?></option></select><linebreak></linebreak>
									<div class="rs_ne_def_meta_wrap" id="rs_ne_def_meta_font-family_val_wrap"><label_a><?php echo __('Default');?></label_a><select id="nav_fontfamily" class="basicinput searchbox tos2" data-evt="updateFontFamily"></select></div>
									<div class="rs_ne_def_meta_wrap" id="rs_ne_def_meta_custom_val_wrap"><label_a><?php echo __('Default');?></label_a><input id="rs_ne_def_meta_custom_val" type="text" /></div>
									<div class="rs_ne_def_meta_wrap" id="rs_ne_def_meta_color_val_wrap"><label_a><?php echo __('Default');?></label_a><input id="rs_ne_def_meta_color_val" type="text" class="my-color-field" data-visible="true" value="#ffffff" data-editing="Meta Color" data-mode="single" name="nav_meta_color" /></div>
									<div class="rs_ne_def_meta_wrap" id="rs_ne_def_meta_icon_val_wrap"><label_a><?php echo __('Default');?></label_a><input id="rs_ne_def_meta_icon_val" type="text"/>
										<div id="rs_ne_icons">
											<div class="font_icon_subcontainer">
												<i class="rs_ne_pick rs_ne_icon_e817 revicon-left-dir" data-content="\e817"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e818 revicon-right-dir" data-content="\e818"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e819 revicon-left-open" data-content="\e819"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e81a revicon-right-open" data-content="\e81a"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e820 revicon-angle-left" data-content="\e820"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e81d revicon-angle-right" data-content="\e81d"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e81f revicon-left-big" data-content="\e81f"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e81e revicon-right-big" data-content="\e81e"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e82a revicon-left-open-1" data-content="\e82a"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e82b revicon-right-open-1" data-content="\e82b"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e822 revicon-left-open-mini" data-content="\e822"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e823 revicon-right-open-mini" data-content="\e823"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e824 revicon-left-open-big" data-content="\e824"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e825 revicon-right-open-big" data-content="\e825"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e836 revicon-left" data-content="\e836"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e826 revicon-right" data-content="\e826"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e82e revicon-left-open-outline" data-content="\e82e"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e82f revicon-right-open-outline" data-content="\e82f"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e82c revicon-left-open-2" data-content="\e82c"></i><!--
												--><i class="rs_ne_pick rs_ne_icon_e82d revicon-right-open-2" data-content="\e82d"></i>
											</div>
										</div>
									</div>
									<label_a><?php echo __('Title');?></label_a><input placeholder="<?php echo __('Can not be Empty');?>" id="rs_ne_def_meta_title" type="text" /><linebreak></linebreak>
									<label_a><?php echo __('Handle');?></label_a><input placeholder="<?php echo __('Can not be Empty');?>" id="rs_ne_def_meta_handle" type="text" /><linebreak></linebreak>
									<div class="rs_ne_add_new_wrap"><div data-evt="closenavmetavalue" class="eventcaller basic_action_button onlyicon autosize"><i class="material-icons">close</i></div><div id="update_nav_meta_value" data-evt="updatenavmetavalue" class="eventcaller basic_action_button onlyicon autosize"><i class="material-icons">done</i></div></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<!-- SLIDER API MODAL -->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_slider_api" data-centerineditor="true">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_slider_api" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">code</i><span class="rbm_title"><?php echo __('CSS/JS Editor');?></span><div class="modal_header_functions"><div data-mode="css" class="selected js_css_editor_tabs"><?php echo __('CUSTOM CSS');?></div><div data-mode="javascript" class="js_css_editor_tabs"><?php echo __('CUSTOM JS');?></div></div></div>
				<div class="emc_toggle_wrap"><div class="emc_toggle_info">A<br>P<br>I</div><i id="emc_toggle" class="material-icons">keyboard_arrow_right</i><i class="rbm_close material-icons">close</i>
					<div class="emc_toggle_inner">
						<!-- MODULE API -->

							<div id="form_module_advanced_api"  data-select="#gst_sl_11" data-unselect=".general_submodule_trigger" class="formcontainer form_menu_inside collapsed">
								<!-- MODULE API INNER-->
								<div id="form_slidergeneral_advanced_api" class="form_inner">
									<div class="form_inner_header"><i class="material-icons">code</i><?php echo __('Methods');?></div>
									<div class="collapsable" style="display:block !important">
										<label_a origtitle="<?php echo __("Call this function to start the slider.");?>"><?php echo __("Start Slider")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly  class="api-input withlabel" id="apiapi0" value="revapi.revstart();">
											<div class="basic_action_button insertineditor mini_action_button onlyicon buttonextension" data-insertfrom="#apiapi0"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Call this function to pause the slider.");?>"><?php echo __("Pause Slider")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly  class="api-input withlabel" id="apiapi1" value="revapi.revpause();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi1"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Call this function to play the slider if it is paused.");?>"><?php echo __("Resume Slider")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi2" value="revapi.revresume();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi2"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Switch slider to previous slide.");?>"><?php echo __("Previous Slide")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi3" value="revapi.revprev();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi3"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Switch slider to next slide.");?>"><?php echo __("Next Slide")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi4" value="revapi.revnext();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi4"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Scroll page under the slider.");?>"><?php echo __("External Scroll")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi9" value="revapi.revscroll(offset);">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi9"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Remove One Slide with Slide Index from the Slider. Index starts with 0 which will remove the first slide.");?>"><?php echo __("Remove Slide")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly  class="api-input withlabel" id="apiapi12" value="revapi.revremoveslide(slideindex);">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi12"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Switch to the slide which is defined as parameter.");?>"><?php echo __("Go To Slide")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi5" value="revapi.revshowslide(2);">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi5"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Switch to the slide which is defined as parameter.");?>"><?php echo __("Go To Slide with ID")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi15" value="revapi.revcallslidewithid('rs-1007');">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi15"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Get the amount of existing slides in the slider.");?>"><?php echo __("Max Slides")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi6" value="revapi.revmaxslide();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi6"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Get the current focused slide index.");?>"><?php echo __("Current Slide")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi7" value="revapi.revcurrentslide();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi7"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Get the previously played slide.");?>"><?php echo __("Last Slide")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly class="api-input withlabel" id="apiapi8" value="revapi.revlastslide();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi8"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Recalculate all positions, sizing etc in the slider.  This should be called i.e. if Slider was invisible and becomes visible without any window resize event.");?>"><?php echo __("Redraw Slider")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly  class="api-input withlabel" id="apiapi10" value="revapi.revredraw();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi10"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Unbind all listeners, remove current animations and delete containers. Ready for Garbage collection.");?>"><?php echo __("Kill Slider")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly  class="api-input withlabel" id="apiapi11" value="revapi.revkill();">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi11"><i class="material-icons">add</i></div>
										</div>

										<label_a origtitle="<?php echo __("Animate a Layer to a predefined Frame");?>"><?php echo __("Go To Frame")?></label_a><!--
										--><div class="input_with_buttonextenstion">
											<input type="text" readonly  class="api-input withlabel" id="apiapi16" value="revapi.revGoToFrame({layerid:'',frame:'',children:true})">
											<div class="buttonextension basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apiapi16"><i class="material-icons">add</i></div>
										</div>
									</div>

								<!-- API EVENTS-->

									<div class="form_inner_header"><i class="material-icons">av_timer</i><?php echo __('Events');?></div>
									<div class="collapsable" style="display:block !important">
										<label_full><?php echo __("Slider Loaded")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent1"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent1" class="api_area" readonly style="height:50px">revapi.bind("revolution.slide.onloaded",function (e) {});</textarea>

										<label_full><?php echo __("Slider swapped to an other slide")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent2"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent2"  class="api_area" readonly style="height:135px">revapi.bind("revolution.slide.onchange",function (e,data){&#013;   //data.slideIndex => <?php echo __('Index of Current Slide');?>&#013;   //data.slideLIIndex => <?php echo __('Current <li> Index');?>&#013;   //data.currentslide => <?php echo __('Current Slide as jQuery Object');?>&#013;   //data.prevslide => <?php echo __('Prev. Slide as jQuery Object');?>&#013;});</textarea>

										<label_full><?php echo __("Slider paused")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent3"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent3"  class="api_area"  readonly style="height:85px">revapi.bind("revolution.slide.onpause",function (e,data) {&#013;   //<?php echo __('Timer Paused');?>&#013;});</textarea>

										<label_full><?php echo __("Slider is Playing after pause")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent4"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent4" class="api_area" readonly style="height:85px">revapi.bind("revolution.slide.onresume",function (e,data) {&#013;   //<?php echo __('Timer Resumed');?>&#013;});</textarea>

										<label_full><?php echo __("Video is playing in slider")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent5"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent5" class="api_area" readonly style="height:135px">revapi.bind("revolution.slide.onvideoplay",function (e,data) {&#013;  //<?php echo __('Video is playing');?>&#013;  //data.video => <?php echo __('Video API');?>&#013;   //data.videotype => <?php echo __('youtube, vimeo, html5');?>&#013;   //data.settings => <?php echo __('Video Settings');?>&#013;});</textarea>

										<label_full><?php echo __("Video stopped in slider")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent6"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent6" class="api_area" readonly style="height:135px">revapi.bind("revolution.slide.onvideostop",function (e,data) {&#013;  //<?php echo __('Video is stopped');?>&#013;  //data.video => <?php echo __('Video API');?>&#013;   //data.videotype => <?php echo __('youtube, vimeo, html5');?>&#013;   //data.settings => <?php echo __('Video Settings');?>&#013;});</textarea>

										<label_full><?php echo __("Slider reached the 'stop at' slide")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent7"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent7" class="api_area" readonly style="height:85px">revapi.bind("revolution.slide.onstop",function (e,data) {&#013;   //<?php echo __('Slider Stopped');?>&#013;});</textarea>

										<label_full><?php echo __("Prepared for slide change")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent8"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent8" class="api_area" readonly style="height:120px">revapi.bind("revolution.slide.onbeforeswap",function (e,data) {&#013;   //<?php echo __('Slider Before Swap');?>&#013;   //data.currentslide => <?php echo __('Current Slide as jQuery Object');?>&#013;   //data.nextslide => <?php echo __('Coming Slide as jQuery Object');?>&#013;});</textarea>

										<label_full><?php echo __("Finnished with slide change")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent9"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent9" class="api_area" readonly style="height:120px">revapi.bind("revolution.slide.onafterswap",function (e,data) {&#013;   //<?php echo __('Slider After Swap');?>&#013;   //data.currentslide => <?php echo __('Current Slide as jQuery Object');?>&#013;   //data.prevslide => <?php echo __('Previous Slide as jQuery Object');?>&#013;});</textarea>

										<label_full><?php echo __("Last slide starts")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent10"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent10" class="api_area" readonly style="height:65px">revapi.bind("revolution.slide.slideatend",function (e) {&#013;   //<?php echo __('Last Slide Started, Slider is at the end');?>&#013;});</textarea>

										<label_full><?php echo __("Layer Events")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent11"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent11" class="api_area"  readonly style="height:150px">revapi.bind("revolution.slide.layeraction",function (e,data) {&#013;   //data.eventtype - <?php echo __('Layer Action (enterstage, enteredstage, leavestage,leftstage)');?>&#013;   //data.layertype - <?php echo __('Layer Type (image,video,html)');?>&#013;   //data.layersettings - <?php echo __('Default Settings for Layer');?>&#013;   //data.layer - <?php echo __('Layer as jQuery Object');?>&#013;});</textarea>

										<label_full><?php echo __("Any Modal Opens")?></label_full><div class="basic_action_button insertineditor mini_action_button onlyicon" data-insertfrom="#apievent12"><i class="material-icons">add</i></div><span class="linebreak"></span>
										<textarea id="apievent12"  class="api_area" readonly style="height:135px">jQuery.fn.revolution.document.on('RS_MODALOPENED', function() {&#013;});</textarea>
									</div><!-- COLLAPSED -->

							</div>
						</div><!-- END OF MODULE API -->
					</div>
				</div>
				<div class="rbm_content" id="rs_css_js_area"></div>
			</div>
		</div>
	</div>
</div>

<!--LAYER META MODAL-->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_layer_metas">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_layer_metas" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">local_offer</i><span class="rbm_title"><?php echo __('Meta Datas');?></span>
					<div id="mdl_group_wrap_menu"><!--
						--><div data-show="mdl_group_post" class="mdl_group_wrap_menuitem selected"><?php echo __('Product');?></div><!--
						--><div data-show="mdl_group_social" class="mdl_group_wrap_menuitem"><?php echo __('Social');?></div>
					</div>
					<i class="rbm_close material-icons">close</i>
				</div>
				<div class="rbm_content" id="meta_rbm_content">
					<div id="meta_datas_list">

						<div id="mdl_group_post" class="mdl_group_wrap selected" data-title="<?php echo __('Product');?>">
							<!-- PRODUCT ATTRIBUTES META DATAS -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="material-icons">description</i><?php echo __('Product Attributes');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{attribute:code}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">description</i><?php echo __("Any custom product attribute");?></div><div class="mdl_right_content">{{attribute:code}}</div><div class="mdl_placeholder_content"><?php echo __('Product Attribute');?></div></div>
								<div data-val="{{name}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">description</i><?php echo __("Product Name");?></div><div class="mdl_right_content">{{name}}</div><div class="mdl_placeholder_content"><?php echo __('Name');?></div></div>
								<div data-val="{{price}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">description</i><?php echo __("Product Price");?></div><div class="mdl_right_content">{{price}}</div><div class="mdl_placeholder_content"><?php echo __('$9.99');?></div></div>
								<div data-val="{{special_price}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">description</i><?php echo __("Product Special Price");?></div><div class="mdl_right_content">{{special_price}}</div><div class="mdl_placeholder_content"><?php echo __('$9.99');?></div></div>
								<div data-val="{{short_description}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">description</i><?php echo __("Short Description");?></div><div class="mdl_right_content">{{short_description}}</div><div class="mdl_placeholder_content"><?php echo __('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.');?></div></div>
								<div data-val="{{description}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">description</i><?php echo __("Description");?></div><div class="mdl_right_content">{{description}}</div><div class="mdl_placeholder_content"><?php echo __('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.');?></div></div>
							</div>

							<!-- PRODUCT LINKS META DATAS -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="material-icons">info</i><?php echo __('Product Links');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{view_link}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">link</i><?php echo __("Link to view product");?></div><div class="mdl_right_content">{{view_link}}</div><div class="mdl_placeholder_content"><?php echo __('http://yoursite.com/link');?></div></div>
								<div data-val="{{cart_link}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">link</i><?php echo __("Add to cart link");?></div><div class="mdl_right_content">{{cart_link}}</div><div class="mdl_placeholder_content"><?php echo __('http://yoursite.com/link');?></div></div>
								<div data-val="{{wishlist_link}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">link</i><?php echo __("Add to wishlist link");?></div><div class="mdl_right_content">{{wishlist_link}}</div><div class="mdl_placeholder_content"><?php echo __('http://yoursite.com/link');?></div></div>
							</div>

							<!-- PRODUCT IMAGES META DATAS -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="material-icons">info</i><?php echo __('Product Images');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{product_image_url_base}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">photo</i><?php echo __("Base Image URL");?></div><div class="mdl_right_content">{{product_image_url_base}}</div><div class="mdl_placeholder_content"><?php echo __('http://yoursite.com/image');?></div></div>
								<div data-val="{{product_image_base}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">photo</i><?php echo __("Base Image");?></div><div class="mdl_right_content">{{product_image_base}}</div><div class="mdl_placeholder_content">&lt;img src="<?php echo FA::getAssetUrl('public/assets/assets/sources/post.png'); ?>" /&gt;</div></div>
								<div data-val="{{product_image_url_thumbnail}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">photo</i><?php echo __("Thumbnail URL");?></div><div class="mdl_right_content">{{product_image_url_thumbnail}}</div><div class="mdl_placeholder_content"><?php echo __('http://yoursite.com/image');?></div></div>
								<div data-val="{{product_image_thumbnail}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">photo</i><?php echo __("Thumbnail");?></div><div class="mdl_right_content">{{product_image_thumbnail}}</div><div class="mdl_placeholder_content">&lt;img src="<?php echo FA::getAssetUrl('public/assets/assets/sources/post.png'); ?>" /&gt;</div></div>
								<div data-val="{{product_image_url_small}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">photo</i><?php echo __("Small Image URL");?></div><div class="mdl_right_content">{{product_image_url_small}}</div><div class="mdl_placeholder_content"><?php echo __('http://yoursite.com/image');?></div></div>
								<div data-val="{{product_image_small}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">photo</i><?php echo __("Small Image");?></div><div class="mdl_right_content">{{product_image_small}}</div><div class="mdl_placeholder_content">&lt;img src="<?php echo FA::getAssetUrl('public/assets/assets/sources/post.png'); ?>" /&gt;</div></div>
							</div>

						</div>

						<div id="mdl_group_social" class="mdl_group_wrap" data-title="<?php echo __('Social');?>">
							<!-- FLICKR -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="material-icons">public</i><?php echo __('Social Basics (Flickr, Instagram, Twitter, Facebook, YouTube)');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{title}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">public</i><?php echo __("Post Title");?></div><div class="mdl_right_content">{{title}}</div><div class="mdl_placeholder_content"><?php echo __('Title');?></div></div>
								<div data-val="{{content}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">public</i><?php echo __("Post content");?></div><div class="mdl_right_content">{{content}}</div><div class="mdl_placeholder_content"><?php echo __('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.');?></div></div>
								<div data-val="{{content:words:10}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">public</i><?php echo __("Post content limit by words");?>	</div><div class="mdl_right_content">{{content:words:10}}</div><div class="mdl_placeholder_content"><?php echo __('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.');?></div></div>
								<div data-val="{{content:chars:10}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">public</i><?php echo __("Post content limit by chars");?>	</div><div class="mdl_right_content">{{content:chars:10}}</div><div class="mdl_placeholder_content"><?php echo __('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt.');?></div></div>
								<div data-val="{{link}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">public</i><?php echo __("The link to the post");?></div><div class="mdl_right_content">{{link}}</div><div class="mdl_placeholder_content"><?php echo __('http://yoursite.com/post');?></div></div>
								<div data-val="{{date}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">public</i><?php echo __("Date created");?></div><div class="mdl_right_content">{{date}}</div><div class="mdl_placeholder_content"><?php echo __('08.03.2018');?></div></div>
								<div data-val="{{author_name}}" class="mdl_group_member"><div class="mdl_left_content"><i class="material-icons">public</i><?php echo __("Username");?></div><div class="mdl_right_content">{{author_name}}</div><div class="mdl_placeholder_content"><?php echo __('John Doe');?></div></div>
							</div>

							<!-- FLICKR -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="fa__icons fa-flickr"></i><?php echo __('Flickr Extras');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{date}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-flickr"></i><?php echo __("Date created");?></div><div class="mdl_right_content">{{date}}</div><div class="mdl_placeholder_content"><?php echo __('08.03.2018');?></div></div>
								<div data-val="{{views}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-flickr"></i><?php echo __("Views");?></div><div class="mdl_right_content">{{views}}</div><div class="mdl_placeholder_content"><?php echo __('24');?></div></div>
							</div>

							<!-- TWITTER -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="fa__icons fa-twitter"></i><?php echo __('Twitter Extras');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{date_published}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-twitter"></i><?php echo __("Date Published");?></div><div class="mdl_right_content">{{date_published}}</div><div class="mdl_placeholder_content"><?php echo __('08.03.2018');?></div></div>
								<div data-val="{{retweet_count}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-twitter"></i><?php echo __("Retweet Count");?></div><div class="mdl_right_content">{{retweet_count}}</div><div class="mdl_placeholder_content"><?php echo __('19824');?></div></div>
								<div data-val="{{favorite_count}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-twitter"></i><?php echo __("Favorite Count");?></div><div class="mdl_right_content">{{favorite_count}}</div><div class="mdl_placeholder_content"><?php echo __('1249');?></div></div>
							</div>

							<!-- FACEBOOK -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="fa__icons fa-facebook"></i><?php echo __('Facebook Extras');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{date_published}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-facebook"></i><?php echo __("Date Published");?></div><div class="mdl_right_content">{{date_published}}</div><div class="mdl_placeholder_content"><?php echo __('08.03.2018');?></div></div>
								<div data-val="{{date_modified}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-facebook"></i><?php echo __("Date Modified");?></div><div class="mdl_right_content">{{date_modified}}</div><div class="mdl_placeholder_content"><?php echo __('18.08.2018');?></div></div>
								<div data-val="{{likes}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-facebook"></i><?php echo __("Number of Likes");?></div><div class="mdl_right_content">{{likes}}</div><div class="mdl_placeholder_content"><?php echo __('212');?></div></div>
							</div>

							<!-- YOUTUBE -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="fa__icons fa-youtube-square"></i><?php echo __('YouTube Extras');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{excerpt}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-youtube-square"></i><?php echo __("Excerpt");?></div><div class="mdl_right_content">{{excerpt}}</div><div class="mdl_placeholder_content"><?php echo __('Excerpt ipsum dolor sit amet, consetetur sadipscing elitr sed diam nonumy.');?></div></div>
								<div data-val="{{date_published}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-youtube-square"></i><?php echo __("Date Published");?></div><div class="mdl_right_content">{{date_published}}</div><div class="mdl_placeholder_content"><?php echo __('08.03.2018');?></div></div>
							</div>

							<!-- VIMEO -->
							<div class="mdl_group">
								<div class="mdl_group_header"><i class="fa__icons fa-vimeo-square"></i><?php echo __('Vimeo Extras');?><i class="material-icons accordiondrop">arrow_drop_down</i></div>
								<div data-val="{{date_published}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-vimeo-square"></i><?php echo __("Date Published");?></div><div class="mdl_right_content">{{date_published}}</div><div class="mdl_placeholder_content"><?php echo __('08.03.2018');?></div></div>
								<div data-val="{{likes}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-vimeo-square"></i><?php echo __("Number of Likes");?></div><div class="mdl_right_content">{{likes}}</div><div class="mdl_placeholder_content"><?php echo __('321');?></div></div>
								<div data-val="{{views}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-vimeo-square"></i><?php echo __("Number of Views");?></div><div class="mdl_right_content">{{views}}</div><div class="mdl_placeholder_content"><?php echo __('1786');?></div></div>
								<div data-val="{{num_comments}}" class="mdl_group_member"><div class="mdl_left_content"><i class="fa__icons fa-vimeo-square"></i><?php echo __("Number of Comments");?></div><div class="mdl_right_content">{{num_comments}}</div><div class="mdl_placeholder_content"><?php echo __('124');?></div></div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!--LAYER ACTION MODAL-->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_layer_action">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_layer_action" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">touch_app</i><span class="rbm_title"><?php echo __('Actions');?></span><i class="rbm_close material-icons">close</i></div>
				<div class="rbm_content">
					<!-- THE LEFT SIDE OF THE AWESOME MODAL WINDOW -->
					<div class="rbm_content_left">

						<div id="layeractions_overview">
							<div id="layeractions_overview_innerwrap">
								<!-- LAYER AND ITS DEPENDENCIES -->
								<div id="layer_with_action_wrap">
									<div id="layer_with_action"></div>
									<div id="layer_width_action_inner_wrap">
										<ul id="layer_depending_wrap" class="layer_depending_wrap"></ul>
										<div id="layer_depending_frames"></div>
										<label_a style="width:175px"><?php echo __('Trigger Memory');?></label_a><select data-r="actions.triggerMemory" class="easyinit layerinput nosearchbox tos2"><option value="reset"><?php echo __('Reset before each Loop');?></option><option value="keep"><?php echo __('Keep Last State');?></option></select>
									</div>
								</div>
								<!-- ACTIONS TRIGGERED BY THE LAYER -->
								<ul id="selected_layer_actions"></ul>
							</div>
							<div id="addactiontolayer" class="rbm_darkbutton"><i class="material-icons">add_circle_outline</i><?php echo __('Add Action to ');?> &quot;<span id="add_action_to_layername"></span>&quot;</span></div>
						</div>

					</div>
					<!-- THE RIGHT SIDE OF THE AWESOME MODAL WINDOW -->
					<div class="rbm_content_right">
						<div id="no_action_selected"><i class="material-icons">info</i><?php echo __('No Action Selected');?></div>

						<!-- THE LIST OF THE ACTIONS -->
						<div id="layeraction_list"></div>

						<!-- INPUT FIELD LIST OF THE SELECTED ACTION -->
						<div id="action_inputs">
							<div id="action_interaction_wrap">
								<select style="display:none !important" id="action_interaction" data-unselect=".layer_action_interaction_selector" data-select="#action_interaction*val*" class="easyinit" data-r="actions.action.#actionindex#.tooltip_event"><option value="click"><?php echo __('Click');?></option><option value="mouseenter"><?php echo __('Mouse Enter');?></option><option value="mouseleave"><?php echo __('Mouse Leave');?></option></select>
								<label_a><?php echo __('Interaction');?></label_a><select id="action_interaction" class="easyinit actioninput tos2 nosearchbox" data-r="actions.action.#actionindex#.tooltip_event"><option value="click"><?php echo __('Click');?></option><option value="mouseenter"><?php echo __('Mouse Enter');?></option><option value="mouseleave"><?php echo __('Mouse Leave');?></option></select>
							</div>
							<!--<label_icon class="triggerselect layer_action_interaction_selector twostatetrigger material-icons selected mirrorhorizontal" data-select="#action_interaction" data-val="click" id="action_interaction_click">near_me</label_icon>
							<label_icon class="triggerselect layer_action_interaction_selector twostatetrigger material-icons" data-select="#action_interaction" data-val="mouseenter" id="action_interaction_mouseenter">file_download</label_icon>
							<label_icon class="triggerselect layer_action_interaction_selector twostatetrigger material-icons" data-select="#action_interaction" data-val="mouseleave" id="action_interaction_mouseleave">file_upload</label_icon>-->
							<!-- TYPE OF ACTION -->
							<label_a><?php echo __('Action Type');?></label_a><div class="input_presets_wrap" id="layer_action_type"><div id="layer_action_fake"></div><input type="text" readonly  class="easyinit actioninput" data-r="actions.action.#actionindex#.action" value=""><i class="material-icons input_presets_dropdown">more_vert</i></div>

							<div class="div20"></div>
							<!-- SIMPLE LINK SETTINGS -->
							<div id="la_settings_link" class="la_settings">
								<label_a><?php echo __('Link URL');?></label_a><input type="text" class="easyinit actioninput" id="la_image_link" data-r="actions.action.#actionindex#.image_link" placeholder="<?php echo __('Enter Link');?>" ><span class="linebreak"></span>
								<label_a><?php echo __('Link Target');?></label_a><select id="la_link_open_in" data-r="actions.action.#actionindex#.link_open_in" class="easyinit actioninput nosearchbox tos2"><option value="_self"><?php echo __('Same Window');?></option><option value="_blank"><?php echo __('New Window');?></option></select>
								<label_a><?php echo __('Link Type');?></label_a><select id="la_link_type" data-r="actions.action.#actionindex#.link_type" class="easyinit actioninput nosearchbox tos2"></select>
								<label_a><?php echo __('Follow');?></label_a><select id="la_link_follow" data-r="actions.action.#actionindex#.link_follow" class="easyinit actioninput nosearchbox tos2"><option value="follow"><?php echo __('Follow Link');?></option><option value="nofollow"><?php echo __('No Follow');?></option></select>
								<span class="linebreak"></span>
							</div>

							<div id="la_settings_modal" class="la_settings">
								<label_a><?php echo __('Open Modal');?></label_a><select id="la_open_modal" data-r="actions.action.#actionindex#.openmodal" data-evt="refreshSlideLists" class="selectsliderlist easyinit actioninput searchbox tos2"></select>
								<label_a><?php echo __('Open Slide');?></label_a><select id="la_open_modalslide" data-r="actions.action.#actionindex#.modalslide" class="selectsliderlist easyinit actioninput searchbox tos2"></select>
							</div>

							<!-- CALL BACK SETTINGS -->
							<div id="la_settings_callback" class="la_settings">
								<label_a><?php echo __('Function');?></label_a><input class="easyinit actioninput" type="text" id="la_actioncallback" data-r="actions.action.#actionindex#.actioncallback" placeholder="<?php echo __('javaScript Function');?>" ><span class="linebreak"></span>
								<span class="linebreak"></span>
							</div>

							<!-- SCROLL TO ID -->
							<div id="la_settings_scroll_to" class="la_settings">
								<label_a><?php echo __('Scroll to ID');?></label_a><input class="easyinit actioninput" type="text" id="la_scrolltoid" data-r="actions.action.#actionindex#.scrollto_id" placeholder="<?php echo __('ID of Element');?>" ><span class="linebreak"></span>
								<span class="linebreak"></span>
							</div>

							<!-- SCROLL BELOW SETTINGS -->
							<div id="la_settings_scroll_under" class="la_settings">
								<label_a><?php echo __('Scroll Offset');?></label_a><input class="easyinit actioninput" type="text" id="la_scrollunder_offset" data-numeric="true" data-allowed="px,%" data-r="actions.action.#actionindex#.scrollunder_offset" placeholder="<?php echo __('Offset to Scroll Position');?>" ><span class="linebreak"></span>
								<label_a><?php echo __('Animation Ease');?></label_a><select id="la_action_easing" class="easyinit actioninput tos2 nosearchbox easingSelect" data-r="actions.action.#actionindex#.action_easing"></select>
								<label_a><?php echo __('Animation Duration');?></label_a><input class="easyinit actioninput" type="text" id="la_saction_speed" data-numeric="true" data-allowed="ms" data-r="actions.action.#actionindex#.action_speed" placeholder="<?php echo __('Animation Duration in ms');?>" ><span class="linebreak"></span>
								<span class="linebreak"></span>
							</div>

							<!-- JUMP TO SLIDE -->
							<div id="la_settings_jumpto" class="la_settings">
								<label_a><?php echo __('Jump to Slide');?></label_a><select id="la_jump_to_slide" data-r="actions.action.#actionindex#.jump_to_slide" class="easyinit actioninput nosearchbox tos2"></select>
								<span class="linebreak"></span>
							</div>

                            <!-- SCROLL BELOW SETTINGS -->
                            <div id="la_settings_getAccelerationPermissionk" class="la_settings">
                                <span class="linebreak"></span>
                            </div>

                            <!-- LAYER TARGET -->
							<div id="la_settings_layertarget" class="la_settings">
								<label_a><?php echo __('Target Layer');?></label_a><select id="la_layer_target" data-evt="refreshActionView" data-theme="layer_selector_drop_down" data-r="actions.action.#actionindex#.layer_target" class="easyinit actioninput nosearchbox tos2"></select>
							</div>


							<!-- LAYER TOGGLE -->
							<div id="la_settings_layer_toggle_actions" class="la_settings">
								<label_a><?php echo __('Toggle Start State');?></label_a><select id="toggle_layer_type" data-evt="refreshLayerToggleState" data-theme="layer_selector_drop_down" data-r="actions.action.#actionindex#.toggle_layer_type" class="easyinit actioninput nosearchbox tos2"><option value="visible"><?php echo __('Toggled (Visible)');?></option><option value="hidden"><?php echo __('Untoggled (Hidden)');?></option></select>
							</div>

							<!-- LAYER ANIMATION IN/OUT -->
							<div id="la_settings_layer_actions_in" class="la_settings">
								<label_a><?php echo __('Frame wait\'s on Action');?></label_a><input id="overtake_frame_1_control" type="checkbox" class="targetlayeractioninput" data-r="timeline.frames.frame_1.timeline.actionTriggered"><span class="linebreak"></span>
							</div>

							<!-- LAYER ANIMATION IN/OUT -->
							<div id="la_settings_layer_actions_out" class="la_settings">
								<label_a><?php echo __('Frame wait\'s on Action');?></label_a><input type="checkbox" id="overtake_frame_999_control" class="targetlayeractioninput" data-r="timeline.frames.frame_999.timeline.actionTriggered"><span class="linebreak"></span>
							</div>

							<!-- LAYER ANIMATION FRAME -->
							<div id="la_settings_layer_actions_frame" class="la_settings">
								<label_a><?php echo __('GoTo Frame');?></label_a><select id="la_gotoframeX"  data-evt="updatePlayFrameXOnlyOnAction" data-evtparam="X" data-r="actions.action.#actionindex#.gotoframe" class="callEvent easyinit actioninput nosearchbox tos2"></select>
								<span class="linebreak"></span>
								<label_a><?php echo __('Frame wait\'s on Action');?></label_a><input type="checkbox" id="overtake_frameX_control" class="targetlayeractioninput " data-r="timeline.frames.frame_2.timeline.actionTriggered"><span class="linebreak"></span>
							</div>

							<!-- LAYER ANIMATION FRAME -->
							<div id="la_settings_layer_actions_frameXY" class="la_settings">
								<div class="div20"></div>
								<label_a><?php echo __('Frame N');?></label_a><select id="la_gotoframeN"  data-evt="updatePlayFrameXOnlyOnAction" data-evtparam="N" data-r="actions.action.#actionindex#.gotoframeN" class="callEvent easyinit actioninput nosearchbox tos2"></select>
								<label_a><?php echo __('Frame M');?></label_a><select id="la_gotoframeM"  data-evt="updatePlayFrameXOnlyOnAction" data-evtparam="M" data-r="actions.action.#actionindex#.gotoframeM" class="callEvent easyinit actioninput nosearchbox tos2"></select>
								<span class="linebreak"></span>
								<label_a><?php echo __('"N" wait\'s on Action');?></label_a><input type="checkbox" id="overtake_frameN_control" class="targetlayeractioninput " data-r="timeline.frames.frame_88.timeline.actionTriggered"><span class="linebreak"></span>
								<label_a><?php echo __('"M" wait\'s on Action');?></label_a><input type="checkbox" id="overtake_frameM_control" class="targetlayeractioninput " data-r="timeline.frames.frame_77.timeline.actionTriggered"><span class="linebreak"></span>
								<div class="div20"></div>
							</div>

							<!-- LAYER CHILDREN TIMELINE RESET IF NEEDED -->
							<div id="la_settings_childrentimelines" class="la_settings">
								<label_a><?php echo __('Reset Children Timelines');?></label_a><input id="update_children_timelines" type="checkbox" class="easyinit actioninput" data-r="actions.action.#actionindex#.updateChildren">
							</div>

							<!-- LAYER ANIMATION IN/OUT -->
							<div id="la_settings_layer_actions" class="la_settings">
								<label_a><?php echo __('After Action');?></label_a><select id="la_triggerMemory" data-r="actions.triggerMemory" class="targetlayeractioninput nosearchbox tos2"><option value="reset"><?php echo __('Reset before each Loop');?></option><option value="keep"><?php echo __('Keep Last State');?></option></select>
								<span class="linebreak"></span>
							</div>

							<!-- LAYER TARGET CLASS-->
							<div id="la_settings_class" class="la_settings">
								<label_a><?php echo __('Class to Toggle');?></label_a><input class="easyinit actioninput" type="text" id="la_toggle_class" data-r="actions.action.#actionindex#.toggle_class" placeholder="<?php echo __('class Name to Toggle');?>" ><span class="linebreak"></span>
							</div>

							<!-- ACTION EXTENSIONS -->
							<div id="layer_action_extension_wrap"></div>

							<!-- DELAY -->
							<div id="laction_delay"><label_a><?php echo __('Action Delay');?></label_a><input class="easyinit actioninput" data-numeric="true" data-allowed="ms" type="text" id="layer_action_delay" data-r="actions.action.#actionindex#.action_delay" placeholder="0"></div>

                            <!-- REPEAT DELAY -->
                            <div id="lraction_delay"><label_a><?php echo __('Trigger Repeat Delay');?></label_a><input class="easyinit actioninput" data-numeric="true" data-allowed="ms" type="text" id="layer_action_repeat" data-r="actions.action.#actionindex#.action_repeats" placeholder="0"></div>
						</div><!-- END OF INPUT FIELD LIST OF THE SELECTED ACTION -->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>