<?php
/**
 * Provide an admin area view for the Slider Modal Options
 *
 * This file is used to markup the admin-facing aspects of the plugin.
 * @author    ThemePunch <info@themepunch.com>
 * @link      https://www.themepunch.com/
 * @copyright 2022 ThemePunch
 */


?>

<!-- UNDERLAY FOR MODALS -->
<div id="rb_modal_underlay"></div>

<!-- DECISION MODAL -->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_decisionModal">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_decisionModal" class="rb_modal form_inner">
				<div class="rbm_header"><i id="decmod_icon" class="rbm_symbol material-icons">info</i><span id="decmod_title" class="rbm_title"><?php echo __('Decision Modal Title');?></span></div>
				<div class="rbm_content">
					<div id="decmod_maintxt"></div>
					<div id="decmod_subtxt"></div>
					<div class="div75"></div>
					<div id="decmod_do_btn" class="rbm_darkhalfbutton mr10"><i id="decmod_do_icon" class="material-icons">add_circle_outline</i><span id="decmod_do_txt"><?php echo __('Do It');?></span></div><!--
					--><div id="decmod_dont_btn" class="rbm_darkhalfbutton"><i id="decmod_dont_icon" class="material-icons">add_circle_outline</i><span id="decmod_dont_txt"><?php echo __('Dont Do It');?></span></div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- PREVIEW MODAL -->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_preview">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_preview" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">search</i><span class="rbm_title"><?php echo __('Preview');?></span><span class="rbm_subtitle"><i class="material-icons">photo</i><span id="rbm_preview_moduletitle">Some Module Title</span></span><span class="rbm_preview_sizes"><i data-ref="d" class="rbm_prev_size_sel material-icons selected">desktop_windows</i><i data-ref="n" class="rbm_prev_size_sel material-icons">laptop</i><i data-ref="t" class="rbm_prev_size_sel material-icons">tablet_mac</i><i data-ref="m" class="rbm_prev_size_sel material-icons">phone_android</i></span><div data-clipboard-action="copy" data-clipboard-target="#copy_shortcode_from_preview" class="copypreviewshortcode basic_action_button autosize rightbutton" style="margin-top:10px;margin-right:30px"><i class="material-icons">content_paste</i><?php echo __('Copy Embed Code');?></div><i class="rbm_close material-icons">close</i></div>
				<div class="rbm_content">
					<input style="position:absolute; top:0px; left:0px;height:0px;width:100%; opacity:0; overflow:hidden; outline:none;border:none" class="inputtocopy" id="copy_shortcode_from_preview" readonly="" value="{{block class=&quot;Nwdthemes\Revslider\Block\Revslider&quot; alias=&quot;slider1&quot;}}">
					<div id="rbm_preview_live"></div>
				</div>
			</div>
		</div>
	</div>
</div>

<!--ADDONS INSTALLATION MODAL-->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_addons">
	<div class="rb-modal-inner">
		<div class="rb-modal-content">
			<div id="rbm_addons" class="rb_modal form_inner">
				<div class="rbm_header"><i class="rbm_symbol material-icons">extension</i><span class="rbm_title"><?php echo __('Addons');?></span><i class="rbm_close material-icons">close</i><div id="check_addon_updates_wrap"><div id="check_addon_updates" class="basic_action_button autosize"><i class="material-icons">refresh</i><?php echo __('Check for Updates');?></div><div id="process_all_addon_updates" class="ale_i_allupdateaddon  basic_action_coloredbutton autosize basic_action_button autosize"><i class="material-icons">get_app</i><?php echo __('Update All');?></div></div></div>
				<div id="addon_overviewheader_wrap">
						<div id="addon_overviewheader" class="addon_overview_header">
							<div class="rs_fh_left"><input class="flat_input" id="searchaddons" type="text" placeholder="<?php echo __('Search Addons...');?>"/></div>
							<div class="rs_fh_right" style="margin-right:-5px">
								<select id="sel_addon_sorting" data-evt="updateAddonsOverview" data-evtparam="#addon_sorting" class="addon_sortby tos2 nosearchbox callEvent" data-theme="autowidthinmodal"><option value="datedesc"><?php echo __('Sort by Date');?></option><option value="pop"><?php echo __('Sort by Popularity');?></option><option value="title"><?php echo __('Sort by Title');?></option></select>
								<select id="sel_addon_filtering" data-evt="updateAddonsOverview" data-evtparam="#addon_filtering" class="addon_filterby tos2 nosearchbox callEvent" data-theme="autowidthinmodal"><option value="all"><?php echo __('Show all Addons');?></option><option value="action"><?php echo __('Action Needed');?></option><option value="installed"><?php echo __('Installed Addons');?></option><option value="notinstalled"><?php echo __('Not Installed Addons');?></option><option value="activated"><?php echo __('Activated Addons');?></option></select>
							</div>
							<div class="tp-clearfix"></div>
						</div>
					</div>
				<div id="rbm_addonlist" class="rbm_content"></div>
				<div id="rbm_addon_details">
					<div class="rbm_addon_details_inner"><div class="div20"></div><div class="ale_i_title"><?php echo __('Slider Revolution Addons');?></div><div class="ale_i_content"><?php echo __('Please select an Addon to start with.');?></div><div class="div20"></div></div>
				</div>
				<div id="rbm_configpanel_savebtn"><i class="material-icons mr10">save</i><span class="rbm_cp_save_text"><?php echo __('Save Configuration');?></span></div>
			</div>
		</div>
	</div>
</div>

<!-- TRACKING MODAL -->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_tracking_firstgo">
    <div class="rb-modal-inner">
        <div class="rb-modal-content">
            <div id="rbm_tracking_firstgo" class="rb_modal form_inner">
                <div id="rbm_des_rocket" class="rbm_deco rbm_des_rocket"></div>
                <div id="rbm_des_charts" class="rbm_deco rbm_des_charts"></div>
                <div id="rbm_des_rsicon" class="rbm_deco rbm_des_rsicon"></div>
                <div class="rbm_header"><i class="rbm_close material-icons">close</i></div>
                <div class="rbm_content">
                    <div class="mcg_page_title"><?php echo __('Help Us Make Slider Revolution Better!'); ?></div>
                    <div class="tracking_content_box">
                        <div class="mcg_page_subtitle"><?php echo __('I agree to share data related to my Slider Revolution usage<br>with the development team to help improve the plugin.'); ?></div>
                        <div class="mcg_page_content"><?php echo __('You can always change this agreement with one click in the Global Settings.'); ?></div>

                        <div class="div25"></div>
                        <purplebutton id="rbm_track_enable" style="display:inline-block;" class=""><?php echo __('Yes, that‘s fine!');?></purplebutton>
                        <div class="div10"></div>
                        <graybutton id="rbm_track_disable" style="display:inline-block;" class=""><?php echo __('No, thanks.');?></graybutton>
                        <div class="div50"></div>
                        <a target="_blank" rel="noopener"  href=" https://www.sliderrevolution.com/plugin-privacy-policy/" class="simpletext smalllink" style="display:inline-block;"><?php echo __('View our detailled data collection policy');?></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--DEACTIVATED WARNING MODAL-->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_notactive_warning">
    <div class="rb-modal-inner">
        <div class="rb-modal-content">
            <div id="rbm_notactive_warning" class="rb_modal form_inner">
                <div class="rbm_header"><i class="rbm_close material-icons">close</i></div>
                <div class="rbm_content">
                    <div class="mcg_page mcg_selected">
                        <div class="dcenter">
                            <div class="bigredwarning"><i class="material-icons">error_outline</i></div>
                            <div class="mcg_page_title warningtext"><?php echo __('URGENT');?></div>
                            <div class="mcg_page_title"><?php echo __('Your Slider Revolution License Has Been Deactivated!');?></div>
                            <div><a class="simpletext smalllink" target="_blank" rel="noopener" href="https://www.sliderrevolution.com/faq/why-was-my-slider-revolution-license-deactivated/?utm_source=admin&utm_medium=button&utm_campaign=srusers&utm_content=deactivatedfaq"><?php echo __('Wondering why this happened? Click here!');?></a></div>
                            <div class="div35"></div>
                            <div class="dr_warningbox">
                                <div class="mcg_page_subtitle"><i class="material-icons warningicon">block</i></div>
                                <div class="div15"></div>
                                <div class="mcg_page_subtitle"><?php echo __('All of the premium features including templates, media assets,<br>and add-ons have been removed from your website.');?></div>
                                <div class="div15"></div>
                                <div class="mcg_page_content"><?php echo __('We can help you restore everything right now, all you have to do is choose one of<br>the options below:');?></div>
                                <div class="div25"></div>
                                <purplebutton id="pb_closeandregister" style="display:inline-block; margin-right:10px" class="mcg_next_page"><?php echo __('Register Licence Key');?></purplebutton>
                                <a target="_blank" rel="noopener"  href="https://codecanyon.net/item/slider-revolution-responsive-magento-extension/9332896?ref=nwdthemes&license=regular&open_purchase_for_item_id=9332896&purchasable=source" style="display:inline-block;" class="bluebutton normal mcg_quit_page"><?php echo __('Buy License Key');?></a>
                                <div class="div10"></div>
                            </div>
                            <div class="div10"></div>
                            <div class="dr_warningbox">
                                <div class="mcg_page_subtitle"><i class="material-icons warningicon">do_not_touch</i></div>
                                <div class="div15"></div>
                                <div class="mcg_page_subtitle"><?php echo __('Please note you don’t have access to Premium 1-on-1 support<br>right now ...');?></div>
                                <div class="div15"></div>
                                <div class="mcg_page_content"><?php echo __('.. however, as soon as you reactivate your license, our top-rated support team will<br>ensure that your website is fully functional.');?></div>
                                <div class="div25"></div>
                                <purplebutton id="pb_closeandregister" style="display:inline-block; margin-right:10px" class="mcg_next_page"><?php echo __('Register Licence Key');?></purplebutton>
                                <a target="_blank" rel="noopener"  href="https://codecanyon.net/item/slider-revolution-responsive-magento-extension/9332896?ref=nwdthemes&license=regular&open_purchase_for_item_id=9332896&purchasable=source" style="display:inline-block;" class="bluebutton normal mcg_quit_page"><?php echo __('Buy License Key');?></a>
                                <div class="div10"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--DEACTIVATED ADDONS WARNING MODAL-->
<div class="_TPRB_ rb-modal-wrapper" data-modal="rbm_notactiveaddon_warning">
    <div class="rb-modal-inner">
        <div class="rb-modal-content">
            <div id="rbm_notactiveaddon_warning" class="rb_modal form_inner">
                <div class="rbm_header"><i class="rbm_close material-icons">close</i></div>
                <div class="rbm_content">
                    <div class="mcg_page mcg_selected">
                        <div class="dcenter">
                            <div class="bigyellowwarning"><i class="material-icons">error_outline</i></div>
                            <div class="mcg_page_title"><?php echo __('There is a problem with some of your<br>Slider Revolution modules');?></div>
                            <div class="simpletext"><?php echo __('These modules are using <a class="smalllink" target="_blank" rel="noopener" href="https://www.sliderrevolution.com/expand-possibilities-with-addons/?utm_source=admin&utm_medium=button&utm_campaign=srusers&utm_content=addons">addons</a> which are deactivated or not installed:');?></a></div>
                            <div class="div45"></div>
                            <div id="list_of_deactivated_addons"></div>
                            <div class="div55"></div>
                            <div class="simpletext"><?php echo __('Press the button below to install & activate<br>all addons required by your modules.'); ?></div>
                            <div class="div40"></div>
                            <purplebutton id="naa_install_all" class="mcg_next_page"><?php echo __('Fix All Addons');?></purplebutton>
                            <div class="div40"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
