<?php /* @var $block Magezon\Blog\Block\Post\Comments */?>
<?php
use Magezon\Blog\Model\Comment;

$dataHelper       = $this->helper('\Magezon\Blog\Helper\Data');
$type             = $dataHelper->getCommentType();
$post             = $this->getCurrentPost();
$comments         = $this->getComments();
$total            = count($comments);
$numberOfComments = (int)$dataHelper->getConfig('post_page/comments/number_of_comments');
?>
<?php if ($post->getAllowComment()) { ?>
	<?php if ($type == Comment::TYPE_NATIVE) { ?>
		<div id="blog-post-comments" class="blog-block blog-commentlist">
			<div class="block-block-title blog-block-title"><h3><span><?= $total ? __('%1 comments', $total) : '' ?></span></h3></div>
			<div class="blog-block-content<?= $total ? ' block-block-content' : ''?>">
				<ul><?= $total ? $this->getCommentsHtml() : '' ?></ul>
				<?= $total ? $block->getPagerHtml() : '' ?>
			</div>
		</div>
        <?php if($total) :?>
            <script>
                require(['jquery'], function($) {
                    $('.blog-comment-reply-link').click(function(e) {
                        var parent = $(this).closest('li');
                        $('.blog-comment-form').insertAfter(parent);
                        $('#ccontent').trigger('focus');
                        var parentId = parseInt($(this).data('parent-id'));
                        $('.blog-comment-form').find('input[name=parent_id]').val(parentId);
                    });
                    $('.cancel-comment-reply-link').click(function(e) {
                        $('.blog-comment-form').insertAfter('.blog-commentlist');
                        $('.blog-comment-form').find('input[name=parent_id]').val(0);
                    });

                    $(document).on('click', '.blog-comment-content-show', function() {
                        $(this).parent().html($(this).attr('data-content').replace(/'/g, '"'));
                    });
                });
            </script>
        <?php endif; ?>
	<?php } ?>
	<?php if ($type == Comment::TYPE_FACEBOOK) { ?>
		<?php $lang = $dataHelper->getCurrentLang(); ?>
		<div class="fb-comments" data-href="<?= $post->getUrl() ?>" data-width="100%" data-numposts="<?= $numberOfComments ?>"></div>
		<div id="fb-root"></div>
		<script async defer crossorigin="anonymous" src="https://connect.facebook.net/<?= $lang ?>/sdk.js#xfbml=1&version=v4.0"></script>
	<?php } ?>
	<?php if ($type == Comment::TYPE_DISQUS) { ?>
		<div id="disqus_thread"></div>
		<script id="dsq-count-scr" src="//blog-m2-magezon-com.disqus.com/count.js" async></script>
		<script>
		var disqus_config = function () {
			this.page.url = '<?php $post->getUrl() ?>';
			this.page.identifier = '<?php $post->getIdentifier() ?>';
		};
		(function() { // DON'T EDIT BELOW THIS LINE
		var d = document, s = d.createElement('script');
		s.src = 'https://blog-m2-magezon-com.disqus.com/embed.js';
		s.setAttribute('data-timestamp', +new Date());
		(d.head || d.body).appendChild(s);
		})();
		</script>
		<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	<?php } ?>
<?php } ?>
