<?php /* @var $block Magezon\Blog\Block\Post\View */?>
<?php
use Magezon\Blog\Model\Comment;

$dataHelper   = $this->helper('Magezon\Blog\Helper\Data');
$commentType  = $dataHelper->getCommentType();
$post         = $this->getCurrentPost();
$author       = $post->getAuthor();
$showPostMeta = $dataHelper->getConfig('post_page/post_meta/enabled');
$showAuthor   = $dataHelper->getConfig('post_page/post_meta/post_author');
$showDate     = $dataHelper->getConfig('post_page/post_meta/post_date');
$showCategory = $dataHelper->getConfig('post_page/post_meta/post_cats');
$showComment  = $dataHelper->getConfig('post_page/post_meta/post_comments');
$showView     = $dataHelper->getConfig('post_page/post_meta/post_views');
$showReadTime = $dataHelper->getConfig('post_page/post_meta/post_read_time');
?>
<?php if ($showPostMeta && ($showAuthor || $showDate || $showCategory || $showComment || $showView || $showReadTime)) { ?>
<div class="blog-post-meta">
	<?php if ($showAuthor && $author) { ?>
	<span class="blog-post-meta-author"><i class="fas mgz-fa-user"></i><?php if ($author->getUrl()) { ?><a href="<?= $author->getUrl() ?>" title="<?= $block->escapeHtml($author->getPublicName()) ?>"><?php } ?><?= $author->getPublicName() ?><?php if ($author->getUrl()) { ?></a><?php } ?></span>
	<?php } ?>
	<?php if ($showDate) { ?>
	<span class="blog-post-meta-date"><i class="far mgz-fa-clock"></i><?= $post->getCreatedAtFormatted() ?></span>
	<?php } ?>
	<?php if ($showCategory) { ?>
	<?php $categories = $post->getCategoryList() ?>
	<?php if ($categories) { ?>
	<span class="blog-post-meta-cats"><i class="fas mgz-fa-folder"></i><?php foreach ($categories as $k => $category) { ?><a href="<?= $category->getUrl() ?>" data-id="<?= $k ?>"><?= $category->getTitle() ?></a><?= (isset($categories[$k+1]) && $categories[$k+1]) ? ', ' : '' ?><?php } ?></span>
	<?php } ?>
	<?php } ?>
	<?php if ($showComment && $post->getAllowComment() && $commentType !== Comment::TYPE_FACEBOOK) { ?>
	<span class="blog-post-meta-comments"><i class="fas mgz-fa-comments"></i>
		<a href="<?= $post->getMetaCommentUrl() ?>">
			<?= $post->getTotalComments() > 1 ? __('%1 Comments', (int)$post->getTotalComments()) : '' ?>
			<?= $post->getTotalComments() == 1 ? __('%1 Comment', (int)$post->getTotalComments()) : '' ?>
			<?= $post->getTotalComments() == 0 ? __('Leave a comment') : '' ?>
		</a>
	</span>
	<?php } ?>
	<?php if ($showView) { ?>
	<?php $totalView = number_format((int)$post->getTotalViews()) ?>
	<span class="blog-post-meta-views"><i class="fas mgz-fa-eye"></i><?= ($totalView > 1) ? __('%1 Views', $totalView) : __('%1 View', $totalView) ?></span>
	<?php } ?>
    <?php if ($showReadTime && !empty($post->getReadTime())) { ?>
        <span class="blog-post-meta-read-time"><i class="fas mgz-fa-book"></i><?= $block->escapeHtml($post->getReadTime()) ?> <?= __('Min read') ?></span>
    <?php } ?>
</div>
<?php } ?>
