<?php /* @var $block Magezon\Blog\Block\Post\RelatedProducts */?>
<?php

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\Action\Action;

$dataHelper           = $this->helper('\Magezon\Blog\Helper\Data');
$compareHelper        = $this->helper('Magento\Catalog\Helper\Product\Compare');
$coreHelper           = $this->helper('Magezon\Core\Helper\Data');
$collection           = $this->getCollection();
$count                = $collection->count();
$id                   = time() . uniqid();
$showImage            = true;
$showName             = true;
$showPrice            = true;
$showShortDescription = false;
$showWishlist         = true;
$showCompare          = true;
$showCart             = true;
$showReview           = true;
$imageId              = 'category_page_grid';
$templateType         = ReviewRendererInterface::SHORT_VIEW;
$lazyLoad             = true;
$title                = $dataHelper->getConfig('post_page/related_products/title');
?>
<?php if ($count) { ?>
<div id="blog-post-relatedproducts" class="blog-block blog-post-relatedproducts">
	<?php if ($title) { ?>
		<div class="block-block-title"><h3><span><?= $title ?></span></h3></div>
	<?php } ?>
	<div class="block-block-content">
		<div id="<?= $id ?>" class="owl-carousel blog-carousel">
			<?php foreach ($collection as $_product) { ?>
				<div class="item product product-item">
					<div class="product-item-info">
						<?php if ($showImage) { ?>
							<?php $productImage = $block->getImage($_product, $imageId); ?>
							<a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php
								$imgHtml = $productImage->toHtml();
								if ($lazyLoad) $imgHtml = $coreHelper->filterCarouselLazyImage($imgHtml);
								?>
								<?= $imgHtml ?>
							</a>
						<?php } ?>
						<div class="product details product-item-details">
							<?php if ($showName) { ?>
								<strong class="product-item-name">
									<a title="<?= $block->escapeHtml($_product->getName()) ?>"
										href="<?= $block->getProductUrl($_product) ?>"
										class="product-item-link">
										<?= $block->escapeHtml($_product->getName()) ?>
									</a>
								</strong>
							<?php } ?>

							<?= $showPrice ? $block->getProductPrice($_product) : '' ?>

							<?= ($templateType && $showReview) ? $block->getReviewsSummaryHtml($_product, $templateType) : '' ?>

							<?php if ($showShortDescription) { ?>
								<div class="product-item-shortdescription"><?= $coreHelper->filter($_product->getShortDescription()) ?></div>
							<?php } ?>

							<?php if ($showWishlist || $showCompare || $showCart) { ?>
								<div class="product-item-actions">
									<?php if ($showCart) { ?>
										<div class="actions-primary">
											<?php if ($_product->isSaleable()) { ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?= $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?= $postParams['data']['product']; ?>">
													<input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED; ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php if ($formKey = $block->getProductFormKey()) { ?>
														<input name="form_key" type="hidden" value="<?= $formKey ?>" />
													<?php } else { ?>
														<?= $block->getBlockHtml('formkey')?>
													<?php } ?>
													<button type="submit"
													title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
													class="action tocart primary">
													<span><?= __('Add to Cart') ?></span>
												</button>
											</form>
										<?php } else { ?>
											<?php if ($_product->getIsSalable()) { ?>
												<div class="stock available"><span><?= __('In stock') ?></span></div>
											<?php } else { ?>
												<div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
											<?php } ?>
										<?php } ?>
									</div>
								<?php } ?>
								<?php if ($showWishlist || $showCompare) { ?>
									<div class="actions-secondary" data-role="add-to-links">
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist) { ?>
											<a href="#"
											data-post='<?= $block->getAddToWishlistParams($_product) ?>'
											class="action towishlist" data-action="add-to-wishlist"
											title="<?= __('Add to Wish List') ?>">
											<span><?= __('Add to Wish List') ?></span>
										</a>
									<?php } ?>
									<?php if ($block->getAddToCompareUrl() && $showCompare) { ?>
										<a href="#" class="action tocompare"
										data-post='<?= $compareHelper->getPostDataParams($_product) ?>'
										title="<?= __('Add to Compare') ?>">
										<span><?= __('Add to Compare') ?></span>
									</a>
								<?php } ?>
							</div>
						<?php } ?>
					</div>
				<?php } ?>
			</div>
		</div>
				</div>
			<?php } ?>
		</div>
		<script>
			require(['jquery', 'Magezon_Core/js/owl.carousel.min'], function($) {
				$('#<?= $id ?>').owlCarousel({
					lazyLoad: true,
					items: 4,
					dots: true,
					responsive: {
						0: {'items': 2},
						544: {'items': 2},
						768: {'items': 3},
						992: {'items': 4},
						1200: {'items': 4}
					}
				});
			})
		</script>
	</div>
</div>
<?php } ?>