<?php /* @var $block Magezon\Blog\Block\Post\RelatedPosts */?>
<?php
$dataHelper = $this->helper('\Magezon\Blog\Helper\Data');
$html       = $this->getPostListHtml();
$title      = $dataHelper->getConfig('post_page/related_posts/title');
?>
<?php if ($html) { ?>
<div class="blog-block blog-post-relatedposts">
	<?php if ($title) { ?>
		<div class="blog-block-title"><h3><span><?= $title ?></span></h3></div>
	<?php } ?>
	<div class="blog-block-content">
		<?= $html ?>
	</div>
</div>
<?php } ?>
