<?php /* @var $block Magezon\Blog\Block\Post\View */?>
<?php
$dataHelper = $this->helper('\Magezon\Blog\Helper\Data');
?>
<?php if ($dataHelper->enableTagPage()) { ?>
	<?php
	$post       = $this->getCurrentPost();
	$collection = $post->getTagCollection();
	$count      = $collection->count();
	?>
	<?php if ($count) { ?>
		<div class="blog-post-tag">
			<span><?= __('Tags') ?></span>
			<?php foreach ($collection as $_tag) { ?>
				<a href="<?= $_tag->getUrl() ?>" rel="tag"><?= $_tag->getTitle() ?></a>	
			<?php } ?>
		</div>
	<?php } ?>
<?php } ?>