<?php
/**
 *
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 *
 */
?>
<generaltranslation></generaltranslation>

<script>
    window.GeneralTranslationJSON = <?php echo $block->getGeneralTranslationJSON(); ?>;
    window.StoreViews = <?php echo $block->getStoreviewsJson(); ?>;
</script>
<script>
    require([
            'PluginCompany_ContactForms/translation/js/general'
        ], function(Translation) {
            return {}
        }
    );
</script>
