<?php
$post        = $this->getCurrentPost();
$type        = $post->getOgType() ? $post->getOgType() : 'article';
$title       = $post->getOgTitle() ? $post->getOgTitle() : ($post->getMetaTitle() ? $post->getMetaTitle() : $post->getTitle());
$image       = $post->getOgImageUrl();
$description = $post->getOgDescription() ? $post->getOgDescription() : $post->getPostExcerpt();
?>
<meta property="og:type" content="<?= $type ?>" />
<meta property="og:title" content="<?= $block->escapeHtmlAttr($block->stripTags($title)) ?>" />
<meta property="og:image" content="<?= $block->escapeUrl($image) ?>" />
<meta property="og:description" content="<?= $block->escapeHtmlAttr($block->stripTags($description)) ?>" />
<meta property="og:url" content="<?= $block->escapeUrl($post->getUrl()) ?>" />