<?php
/**@var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset $block */
?>
<?php
$_element      = $block->getElement();
$_jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $_element->getHtmlId();
?>
<div class="rule-tree">
    <fieldset id="<?= $_jsObjectName ?>" <?= $_element->serialize(['class']) ?> class="fieldset">
        <legend class="legend"><span><?= $_element->getLegend() ?></span></legend><br>
        <?php if ($_element->getComment()): ?>
            <div class="messages">
                <div class="message message-notice"><?php echo $block->escapeHtml($_element->getComment()) ?></div>
            </div>
        <?php endif; ?>
        <div class="rule-tree-wrapper">
            <?php echo $_element->getChildrenHtml() ?>
        </div>
    </fieldset>
</div>
<script>
    require([
        "Magento_Rule/rules",
        "jquery",
        "prototype"
    ], function(VarienRulesForm, $){
        window.<?= $_jsObjectName ?> = new VarienRulesForm('<?= $_jsObjectName ?>', '<?= $block->getNewChildUrl() ?>');
        <?php if ($_element->getReadonly()): ?>
            <?php echo $_element->getHtmlId() ?>.setReadonly(true);
        <?php endif; ?>
        $('#<?= $_jsObjectName ?>').find('.rule-chooser').each(function(index, el) {
            var ruleChooserUrl = jQuery(this).attr('url');
            ruleChooserUrl += 'form/<?= $_jsObjectName ?>';
            jQuery(this).attr('url', ruleChooserUrl);
        });
    });
</script>