<?php
use Magezon\Blog\Model\Comment;

$dataHelper   = $this->helper('Magezon\Blog\Helper\Data');
$commentType  = $dataHelper->getCommentType();
$collection   = $this->getCollection();
$count        = $collection->count();
$showAuthor   = $this->getShowAuthor();
$showDate     = $this->getShowDate();
$showImage    = $this->getShowImage();
$showCategory = $this->getShowCategory();
$showComment  = $this->getShowComment();
$showView     = $this->getShowView();
?>
<?php if ($count) { ?>
	<div class="blog-post-list">
		<div class="blog-post-listing blog-post-listing2">
			<?php foreach ($collection as $post) { ?>
				<div class="blog-post-box blog-post-type-<?= $post->getType() ?>">
					<div class="blog-post-box-inner">
						<?php $author = $post->getAuthor() ?>
						<?php if ($showImage && ($imageUrl = $post->getImageUrl())) { ?>
							<div class="blog-post-image"><a href="<?= $post->getUrl() ?>" title="<?= $block->escapeHtml($post->getTitle()) ?>"><img src="<?= $imageUrl ?>" alt="<?= $block->escapeHtml($post->getTitle()) ?>"/><span class="blog-post-overlay"></span></a></div>
						<?php } ?>
						<h3 class="blog-post-box-title"><a href="<?= $post->getUrl() ?>" title="<?= $block->escapeHtml($post->getTitle()) ?>"><?= $post->getTitle() ?></a></h3>
						<?php if ($showAuthor || $showDate || $showCategory || $showComment) { ?>
							<div class="blog-post-meta">
								<?php if ($showAuthor && $author) { ?>
									<span class="blog-post-meta-author"><i class="fas mgz-fa-user"></i><?php if ($author->getUrl()) { ?><a href="<?= $author->getUrl() ?>" title="<?= $block->escapeHtml($author->getPublicName()) ?>"><?php } ?><?= $author->getPublicName() ?><?php if ($author->getUrl()) { ?></a><?php } ?></span>
								<?php } ?>
								<?php if ($showDate) { ?>
									<span class="blog-post-meta-date"><i class="far mgz-fa-clock"></i><?= $post->getCreatedAtFormatted(true) ?></span>
								<?php } ?>
								<?php if ($showCategory) { ?>
									<?php $categories = $post->getCategoryList() ?>
									<?php if ($categories) { ?>
										<span class="blog-post-meta-cats"><i class="fas mgz-fa-folder"></i><?php foreach ($categories as $k => $category) { ?><a href="<?= $category->getUrl() ?>" data-id="<?= $k ?>"><?= $category->getTitle() ?></a><?= (isset($categories[$k+1]) && $categories[$k+1]) ? ', ' : '' ?><?php } ?></span>
									<?php } ?>
								<?php } ?>
								<?php if ($showComment && $post->getAllowComment() && ($commentType !== Comment::TYPE_FACEBOOK)) { ?>
									<span clas="blog-post-meta-comments"><i class="fas mgz-fa-comments"></i><a href="<?= $post->getMetaCommentUrl() ?>"><?= (int)$post->getTotalComments() ?></a></span>
								<?php } ?>
								<?php if ($showView) { ?>
									<span clas="blog-post-meta-views"><i class="fas mgz-fa-eye"></i><?= number_format((int)$post->getTotalViews()) ?></span>
								<?php } ?>
							</div>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
<?php } ?>