<?php
use Magezon\Blog\Model\Comment;

$coreHelper      = $this->helper('Magezon\Core\Helper\Data');
$uid             = 'blog-' . time() . uniqid();
$dataHelper      = $this->helper('Magezon\Blog\Helper\Data');
$commentType     = $dataHelper->getCommentType();
$collection      = $this->getCollection();
$count           = $collection->count();
$showAuthor      = $this->getShowAuthor();
$showDate        = $this->getShowDate();
$showImage       = $this->getShowImage();
$showCategory    = $this->getShowCategory();
$showComment     = $this->getShowComment();
$showView        = $this->getShowView();
$showReadTime    = $this->getShowReadTime();
$showExcerpt     = $this->getShowExcerpt();
$carouselOptions = $this->getOwlCarouselOptions();
?>
<?php if ($count) { ?>
	<div id="<?= $uid ?>" class="owl-carousel blog-carousel">
		<?php foreach ($collection as $post) { ?>
			<?php $author = $post->getAuthor() ?>
			<div class="blog-post-box blog-post-type-<?= $post->getType() ?>">
				<div class="blog-post-box-inner">
				<?php if ($showImage && ($imageUrl = $post->getImageUrl(600, 400))) { ?>
				<div class="blog-post-image"><a href="<?= $post->getUrl() ?>" title="<?= $block->escapeHtml($post->getTitle()) ?>"><img src="" class="owl-lazy" data-src="<?= $imageUrl ?>" alt="<?= $block->escapeHtml($post->getTitle()) ?>" width="100%" /><span class="blog-post-overlay"></span></a></div>
				<?php } ?>
				<h3 class="blog-post-box-title"><a href="<?= $post->getUrl() ?>" title="<?= $block->escapeHtml($post->getTitle()) ?>"><?= $post->getTitle() ?></a></h3>
				<?php if ($showAuthor || $showDate || $showCategory || $showComment || $showView || $showExcerpt) { ?>
				<div class="blog-post-meta">
					<?php if ($showAuthor && $author) { ?>
					<span class="blog-post-meta-author"><i class="fas mgz-fa-user"></i><?php if ($author->getUrl()) { ?><a href="<?= $author->getUrl() ?>" title="<?= $block->escapeHtml($author->getPublicName()) ?>"><?php } ?><?= $author->getPublicName() ?><?php if ($author->getUrl()) { ?></a><?php } ?></span>
					<?php } ?>
					<?php if ($showDate) { ?>
					<span class="blog-post-meta-date"><i class="far mgz-fa-clock"></i><?= $post->getCreatedAtFormatted(true) ?></span>
					<?php } ?>
					<?php if ($showCategory) { ?>
					<?php $categories = $post->getCategoryList() ?>
					<?php if ($categories) { ?>
					<span class="blog-post-meta-cats"><i class="fas mgz-fa-folder"></i><?php foreach ($categories as $k => $category) { ?><a href="<?= $category->getUrl() ?>" data-id="<?= $k ?>"><?= $category->getTitle() ?></a><?= (isset($categories[$k+1]) && $categories[$k+1]) ? ', ' : '' ?><?php } ?></span>
					<?php } ?>
					<?php } ?>
					<?php if ($showComment && $post->getAllowComment() && ($commentType !== Comment::TYPE_FACEBOOK)) { ?>
					<span class="blog-post-meta-comments"><i class="fas mgz-fa-comments"></i><a href="<?= $post->getMetaCommentUrl() ?>"><?= (int)$post->getTotalComments() ?></a></span>
					<?php } ?>
					<?php if ($showView) { ?>
					<span class="blog-post-meta-views"><i class="fas mgz-fa-eye"></i><?= number_format((int)$post->getTotalViews()) ?></span>
					<?php } ?>
                    <?php if ($showReadTime && !empty($post->getReadTime())) { ?>
                        <span class="blog-post-meta-read-time"><i class="fas mgz-fa-book"></i><?= $block->escapeHtml($post->getReadTime()) ?> <?= __('Min read') ?></span>
                    <?php } ?>
				</div>
				<?php } ?>
				<?php if ($showExcerpt) { ?>
				<div class="blog-post-excerpt-wrapper">
					<?php if ($excerpt = $post->getPostExcerpt()) { ?>
					<div class="blog-post-excerpt"><?= $excerpt ?></div>
					<?php } ?>
					<a class="blog-post-more-link" href="<?= $post->getUrl() ?>"><?= __('Read More »') ?></a>
				</div>
				<?php } ?>
				</div>
			</div>
		<?php } ?>
	</div>
	<script>
		require(['jquery', 'Magezon_Core/js/owl.carousel.min'], function($) {
			<?php if ($carouselOptions) { ?>
				$('#<?= $uid ?>').owlCarousel(<?= $coreHelper->serialize($carouselOptions) ?>);
			<?php } else { ?>
				$('#<?= $uid ?>').owlCarousel({
					lazyLoad: true,
					items: 4,
					dots: true,
					margin: 15,
					responsive: {
						0: {'items': 1},
						544: {'items': 2},
						768: {'items': 3},
						992: {'items': 4},
						1200: {'items': 4}
					}
				});
			<?php } ?>
		})
	</script>
<?php } ?>