<style type="text/css">
div.block-compare{
    top: 60%;
    transform: translateY(-50%);
    width: 225px;
    padding: 10px 20px;
    position: fixed;
    z-index: 999;
    left: 0;
    margin-bottom: 0;
    background-color: white;
    -webkit-box-shadow: rgb(0 0 0 / 20%) 1px 1px 5px;
    box-shadow: rgb(0 0 0 / 20%) 1px 1px 5px;
    border: 2px solid #f05a1e;
    border-radius: 5px;
} 
.btn-remove{
    float: right;
    display: inline-block;
    width: 20px;
    height: 20px;
    text-align: center;
    font: 0/0 a;
    text-shadow: none;
    color: transparent;
    position: relative;
}
.btn-remove:after {
    content: '\00d7';
    color: #666;
    height: 20px;
    line-height: 20px;
    width: 100%;
    font-size: 24px;
    font-weight: bold;
    font-family: initial;
    display: inline-block;
}
</style>

<div class="mio-compare" data-bind="scope: 'compareProducts'" data-role="compare-products-sidebar">
    <div class="block-compare no-display" data-bind="css: {'no-display': !compareProducts().count}">
        <div class="block-title">
            <strong id="block-compare-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Compare Products')) ?></strong>
            <span class="counter qty no-display" data-bind="text: compareProducts().count, css: {'no-display': !compareProducts().count}"></span>

        </div>
        <!-- ko if: compareProducts().count -->
        <div class="block-content no-display" aria-labelledby="block-compare-heading" data-bind="css: {'no-display': !compareProducts().count}">
            <ol id="compare-items" class="product-items product-items-names" data-bind="foreach: compareProducts().items">
                    <li class="product-item">
                        <input type="hidden" class="compare-item-id" data-bind="value: id"/>
                        <span>
                            <a data-bind="attr: {href: product_url}, html: name" class="product-item-link"></a>
                        </span>
                        <a href="#"
                           data-bind="attr: {'data-post': remove_url}"
                           title="<?= $block->escapeHtmlAttr(__('Remove This Item')) ?>"
                           class="action btn-remove">
                            <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
                        </a>
                    </li>
            </ol>
            <div class="actions-toolbar">
                <div class="primary">
                    <a data-bind="attr: {'href': compareProducts().listUrl}" target="_blank" class="action compare button"><span><?= $block->escapeHtml(__('Compare')) ?></span></a>
                </div>
                <div class="secondary">
                    <a id="compare-clear-all" href="#" class="action clear" data-post="<?=$block->escapeHtml(
                        $this->helper(Magento\Catalog\Helper\Product\Compare::class)->getPostDataClearList()
                    ) ?>">
                        <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                    </a>
                </div>
            </div>
        </div>
        <!-- /ko -->
        <!-- ko ifnot: compareProducts().count -->
        <div class="empty"><?= $block->escapeHtml(__('You have no items to compare.')) ?></div>
        <!-- /ko -->
    </div>
</div>
<script type="text/x-magento-init">
{"[data-role=compare-products-sidebar]": {"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>}}
</script>
