 <div id="layerednav-list-products">
 	<?php 
 	switch($block->showDisplayMode()){
 		case 'TYPE1':
 			echo $block->getProductType1();
 		break;
		case 'TYPE2':
			echo $block->getProductType2();
		break;
		case 'TYPE3':
			echo $block->getProductType3();
		break;
		case 'TYPE4':
		   echo $block->getProductType4();
		break;
		case 'TYPE7':
		   echo $block->getProductType7();
		break;
		case 'TYPE9':
			echo $block->getProductType9();
		break;
 		default:
 			echo $block->getProductType1();
 		break;
 	}

 	?>
 </div>
 <script type="text/x-magento-init">
 	{
 		".quickview-product [data-role=quickview-button]": {
 			"productQuickview": {}
 		}
 	}
 </script>