<?php /* @var $block Magezon\Blog\Block\Sidebar\Archives */?>
<?php
$dataHelper       = $this->helper('\Magezon\Blog\Helper\Data');
$title            = $dataHelper->getConfig('sidebar/archives/title');
$showProductCount = $dataHelper->getConfig('sidebar/archives/show_post_count');
$archives         = $this->getArchives();
?>
<?php if ($archives) { ?>
<div id="blog-archives" class="blog-block blog-archives">
	<?php if ($title) { ?>
		<div class="block-block-title"><h3><span><?= $title ?></span></h3></div>
	<?php } ?>
	<div class="block-block-content">
		<ul>
		<?php foreach ($archives as $year) { ?>
			<?php foreach ($year as $archive) { ?>
				<li><a href="<?= $archive['url'] ?>"><span><?= $archive['label'] ?></span> <?php if ($showProductCount) { ?><span>(<?= $archive['count'] ?>)</span><?php } ?></a></li>
				<?php } ?>
		<?php } ?>
		</ul>
	</div>
</div>
<?php } ?>