<?php /* @var $block Magezon\Blog\Block\Sidebar\FeaturedPosts */ ?>
<?php
$collection = $block->getCollection();
?>

<?php if($collection->count() && $block->getFeaturedPostsEnabled()) :?>
    <div id="blog-featured-posts" class="blog-block blog-featured-posts">
        <div class="block-block-title">
            <h3><span><?= $block->getFeaturedPostsTitleConfig() ?? __('Featured Posts') ?></span></h3>
        </div>
        <div class="block-block-content">
            <div id="featured-posts" class="owl-carousel blog-carousel">
                <?php foreach ($collection as $post) { ?>
                    <?php $author = $post->getAuthor() ?>
                    <div class="blog-post-box blog-post-type-<?= $post->getType() ?>">
                        <div class="blog-post-box-inner">
                            <?php if(!empty($post->getImageUrl())) :?>
                                <div class="blog-post-image">
                                    <a href="<?= $post->getUrl() ?>" title="<?= $block->escapeHtml($post->getTitle()) ?>">
                                        <img src="" class="owl-lazy" data-src="<?= $block->escapeUrl($post->getImageUrl()) ?>" alt="<?= $block->escapeHtml($post->getTitle()) ?>" width="600" height="400"/>
                                        <span class="blog-post-overlay"></span>
                                    </a>
                                </div>
                            <?php endif; ?>
                            <h3 class="blog-post-box-title">
                                <a href="<?= $post->getUrl() ?>" title="<?= $block->escapeHtml($post->getTitle()) ?>"><?= $post->getTitle() ?></a>
                            </h3>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <script>
        require(['jquery', 'Magezon_Core/js/owl.carousel.min'], function ($) {
            $('#featured-posts').owlCarousel({
                lazyLoad: true,
                items: 1,
                dots: true,
                margin: 15,
            });
        })
    </script>
<?php endif; ?>