<?php
$dataHelper = $this->helper('\Magezon\Blog\Helper\Data');
$mainColor  = $dataHelper->getConfig('general/main_color');
$imageUrl  	= $dataHelper->getLoadingImage();
?>
<?php if ($mainColor) { ?>
<style>
	.blog-post-list .pages .item.current .page,
	.blog-post-listing .blog-post-more-link,
	.blog-carousel .blog-post-more-link,
	.blog-post-view .blog-post-social > span,
	.blog-searchform button,
	.blog-tags a:hover,
	.blog-carousel .owl-dots .owl-dot.active span,
	.blog-carousel .owl-dots .owl-dot:hover span {
		background: <?= $mainColor ?>;
	}
	.blog-post-listing .blog-post-box-title a:hover,
	.blog-post-meta a:hover,
	.blog-post-view .blog-post-author .blog-author-name a:hover,
	.blog-block a:hover,
	.blog-categories li.current > a  {
		color: <?= $mainColor ?>;
	}
	.blog-searchform input:focus {
		border-color: <?= $mainColor ?>;
	}
	.blog-post-listing,
	.blog-post-view .blog-post-inner,
	.blog-block .block-block-content,
	.blog-tabs .blog-post-listing,
	.blog-recentcomments {
		border-bottom: 4px solid <?= $mainColor ?>;
	}
</style>
<?php } ?>
<style type="text/css">
	.ajax-loading-comment{ 
		background:url('<?= $imageUrl ?>') no-repeat center center;
	    width: 100%;
    	height: 100%;
	}
</style>