<?php /* @var $block Magezon\Blog\Block\Sidebar */?>
<?php
$dataHelper = $this->helper('Magezon\Blog\Helper\Data');
$blocks     = ['search_form', 'categories', 'archives', 'tags', 'tabs', 'featured_posts'];
$list       = [];
foreach ($blocks as $key) {
	if ($dataHelper->getConfig('sidebar/' . $key . '/enabled')) {
		$sortOrder = (int)$dataHelper->getConfig('sidebar/' . $key . '/sort_order');
		$list[$key] = $sortOrder;
	}
}
asort($list);
?>
<?php foreach (array_keys($list) as $key) { ?>
	<?= $this->getChildHtml($key) ?>
<?php } ?>