<?php
/*Type1:PRODUCTS Default Normal Product Listing */
use Magento\Framework\App\Action\Action;

//For Correct Salable Qty
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');


$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div>
            <?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?>
        </div>
    </div>
<?php else: ?>
    <!-- <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?> -->
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <style>
        .products-grid li.item {
            float: none;
        }

        #limiter {
            padding: 4px 35px 5px 10px;
        }
    </style>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product):
                $saleQty = $stockState->execute($_product->getSku(), 1);
                $productInfo = $block->getProductbyId($_product->getId());

                ?>
                <li class="row col-12 item product product-item">
                    <div class="product-item-info col-md-6" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo"
                            tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                    </div>
                    <div class="product details product-item-details col-md-6">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h2 class="product name product-item-name">
                            <a class="product-item-link" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </h2>
                        <div class="short-desc">
                            <?= $_product->getShortDescription() ?>
                        </div>

                        <?php if ($_product->isAvailable()): ?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>

                        <div class="product-item-inner">
                            <div class="product description product-item-description">
                                <?= /* @noEscape */ $productInfo->getDescription() ?>
                            </div>

                            <div class="ppbd-product-price">
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            </div>
                            <div class="actions">
                                <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                    title="<?= /* @noEscape */ $_productNameStripped ?>"
                                    class="button action more"><?= $block->escapeHtml(__('Learn More')) ?></a>

                                <div data-role="add-to-links" class="actions-secondary link-compare">
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {
                            "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                        }
                    }
                }
                </script>
    <?php endif; ?>
<?php endif; ?>
<script>
    //<![CDATA[
    requirejs([
        'jquery',
    ], function ($) {
        if ($.fn.applyBindings != undefined) {
            $('.compare-items').applyBindings();
        }
    });
    //]]>

    document.addEventListener("DOMContentLoaded", function() {
        var compareLinks = document.querySelectorAll('a.action.tocompare');

        compareLinks.forEach(function(link) {
            var icon = document.createElement('i');
            icon.className = 'fas mgz-fa-plus-square';

            var span = link.querySelector('span');

            if (span) {
                link.insertBefore(icon, span);
            }
        });
    });
</script>