<!-- Type4:DEVICES_PREVIOUS -->
<style type="text/css">
	.fix-search{
		position: fixed;
		right: 0;
		top: 100px;
		width: 25%;
	}
	.products-grid li.item{
		float: none;
	}
	#productSearch{
		text-align: center;
		z-index: 1000;
	}
</style>
<?php
$category = $block->getCurrentCategory();
$currentCategoryId = $category->getId();
$parentCategoryUrl = $category->getParentCategory()->getUrl();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$storeManager = $objectManager->create('Magento\Store\Model\StoreManagerInterface');
$StoreId = $storeManager->getStore()->getStoreId();

$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');

// Hard code the maps / accessories (or need to change get in category)
$mapUrl = $storeManager->getStore()->getBaseUrl().'products/maps';
$accessoriesUrl = $storeManager->getStore()->getBaseUrl().'products/accessories';
?>

<!--<div id="productSearch" class="module-search well fix-search">
	<div class="buttons-set">
		<a class="button button_s secondary" href="<?//=$parentCategoryUrl?>"><?//= $block->escapeHtml(__('Current Range')) ?></a>			 
		<a class="button button_s secondary" href="<?//=$mapUrl?>"><?//= $block->escapeHtml(__('Shop Maps')) ?></a>			 
		<a class="button button_s secondary" href="<?//=$accessoriesUrl?>"><?//= $block->escapeHtml(__('Shop Accessories')) ?></a>		
	</div>
</div>-->

<?php
$mediaUrl = $block->getMediaUrl();
$mioblock = $block->getLayout()->createBlock('Mitac\CustomCMS\Block\Catalog\Products');
$TempProducts = $block->getLegacyAccessory($currentCategoryId);

if(!empty($TempProducts))
{
	ksort($TempProducts);
	?>
	<div class="products wrapper grid products-grid">
		<ol id="accessoriesProducts" class="products list items product-items">
			<?php
			foreach($TempProducts as $product)
			{
				$productInfo = $productRepository->getById($product['ProductId']);
				$VisibilityValue = $productInfo->getResource()->getAttributeRawValue($product['ProductId'],'visibility',$StoreId); //change attribute_code

				if($product['ProductStatus']==1 and ($VisibilityValue==2 or $VisibilityValue==4))
				{
					?>
					<li class="item product product-item">
						<div class="product-image">
							<a href="<?= $block->escapeUrl($product['ProductUrl']) ?>">
								<?php 
								if($product['ProductSmallImage']=='no_selection'||!file_exists('../pub/media/catalog/product'.$product['ProductSmallImage']))
								{
									?>
									<!-- Mio_logo_180X120,Mio_logo_600X400,Mio_logo_600X600 -->
									<img src="<?=$mediaUrl.'mio/images/default/Mio_logo_600X400.jpg'?>">
									<?php 
								}
								else
								{
									?>
									<img src="<?=$mediaUrl.'catalog/product'.$product['ProductSmallImage']?>">
									<?php 
								}
								?>
							</a>
						</div>
						<div class="product details product-item-details">
							<strong class="product name product-item-name">
								<a class="product-item-link" href="<?= $block->escapeUrl($product['ProductUrl']) ?>">
									<?= $block->escapeHtml($product['ProductName']) ?>
								</a>
							</strong>
							<div class="actions">
								<div class="product description product-item-description">
									<?php $description_content = $product['ProductDescription'];?>
									<?= $mioblock->truncate($description_content,240);?>	
								</div>
								<a class="button btn secondary" href="<?= $block->escapeUrl($product['ProductUrl']) ?>"
                                    title="<?= /* @noEscape */ $product['ProductName'] ?>">
                                    <?= $block->escapeHtml(__('Learn More')) ?>
                                </a>
							</div>
						</div>		
					</li>
					<?php
				}
			}
			?>
		</ol>
	</div>
	<?php
}
?>