<?php
$_productCollection = $block->getLoadedProductCollection();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
?>
<!-- [ ]: remove -->
<!-- <div style="padding: 4px; border: 1px solid #999999; border-radius: 8px; background-color: greenyellow; margin-bottom: 10px;">
  <p style="margin: 0;"><strong>agent: </strong></p>
  <p style="margin: 0;"><?= $objectManager->get('\Magento\Framework\App\Request\Http')->getHeader('User-Agent') ?></p>
</div> -->

<?php
if ($_productCollection->count() > 0):
  ?>

  <div class="product-list mionext">
    <?php foreach ($_productCollection as $_product): ?>
      <div class="product card">
        <div class="card-header">
          <h1 class="product-name">
            <?= $_product->getName() ?>
          </h1>
          <div class="short-desc">
            <?= $_product->getShortDescription() ?>
          </div>
        </div>
        <div class="card-body">
          <div class="product-price">
            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
          </div>
          <div class="product-inner">
            <div class="description">
              <?= $_product->getDescription() ?>
            </div>
            <div class="action">
              <?php
                $saleQty = $stockState->execute($_product->getSku(), 1);;
                if ($_product->isSaleable() && $saleQty>0):
              ?>
								<?php $postParams = $block->getAddToCartPostParams($_product); ?>
									<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
										action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
									<input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>" />
									<input type="hidden" name="<?= \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED ?>" value="<?= $postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED] ?>" />
									<?= $block->getBlockHtml('formkey') ?>
										<button type="submit" title="<?= $block->escapeHtml(__('Confirm Payment')) ?>" class="action button">
											<span>
												<?= $block->escapeHtml(__('Confirm Payment')) ?>
											</span>
										</button>
									</form>
								<?php endif; ?>
            </div>
          </div>
        </div>
      </div>
    <?php endforeach; ?>
  </div>

<?php else: ?>
  <div class="message info empty">
    <div>
      <?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?>
    </div>
  </div>
<?php endif; ?>