<?php
/*Type3:Device_MAPS */

use Magento\Framework\App\Action\Action;

if (!empty($_GET['devices'])) {
    $devicesPost = trim($_GET['devices']);
    $device = $block->getAssociatedMaps($devicesPost);
}

//For Correct Salable Qty
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');

$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$AllMapProducts = $block->getAllMapsProduct();
$mediaUrl = $block->getMediaUrl();
$isCartEnabled = $this->helper('Mitac\SystemAPI\Helper\Config')->getIsCartEnabled();

?>

<style>
    #maincontent .columns .column.main {
        padding-top: 0px;
    }

    #productSearch {
        text-align: center;
        z-index: 1000;
    }

    #minicart-content-wrapper {
        display: none;
    }

    .minicart-wrapper.active #minicart-content-wrapper {
        display: block;
    }

    #mapProductList {
        list-style-type: none;
        padding: 0;
        margin: 0;
        position: absolute;
        width: 100%;
        z-index: 1000;
    }

    #mapProductList li {
        display: none;
        text-align: left;
    }

    #mapProductList li a {
        border: 1px solid #ddd;
        margin-top: -1px;
        /* Prevent double borders */
        background-color: #f6f6f6;
        padding: 10px;
        text-decoration: none;
        font-size: 14px;
        color: black;
        display: block
    }

    #mapProductList li a:hover:not(.header),
    #mapProductList li.selected a {
        background-color: #eee;
    }
</style>
<label
    class="d-block text-center searchTitle"><?= $block->escapeHtmlAttr(__('PLEASE ENTER YOUR MODEL BELOW')); ?></label>
<div id="productSearch" class="module-search well">
    <form id="product-search-map" method="GET">
        <div class="input-box">
            <input data-mage-init='{
                "searchMaps": {
                    "formSelector":"#product-search-map",
                    "appendSelector":"#mapProductList"
                }
            }' type="text" id="new-search" name="devices" class="input-text" autocomplete="off"
                value="<?= (isset($_GET['devices'])) ? $_GET['devices'] : '' ?>"
                placeholder="<?= $block->escapeHtmlAttr(__('Search')); ?>">

            <ul id="mapProductList">
                <?php foreach ($AllMapProducts as $value) { ?>
                    <li><a href="?devices=<?= $value['title'] ?>"><?= $value['title'] ?></a></li>
                <?php } ?>
            </ul>
            <button type="submit" title="Search" class="button search-button">
                <span class="ico-search"></span>
            </button>
        </div>
        <div data-block="dropdown" class="minicart-wrapper" style="float:none">
            <button type="button" class="tooltipBtn" data-trigger="trigger">
                <span class="icon-help-circled"></span>
            </button>
        </div>
    </form>

    <div class="block block-minicart" data-mage-init='{
        "dropdownDialog": {
            "triggerEvent" : "click mouseenter",
            "appendTo": "[data-block=dropdown]",
            "triggerTarget":"[data-trigger=trigger]",
            "closeOnMouseLeave": true,
            "closeOnEscape": true,
            "triggerClass": "active",
            "parentClass": "active",
            "buttons": [],
            "responsive": true
        }
    }'>
        <div id="minicart-content-wrapper">
            Please select your device first, so we can filter the correct accessories for you.<br />
            <img src='<?= $block->getMediaUrl() . 'mio/images/maps/model.jpg' ?>' alt='model name' width='100%' />
        </div>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            var wrap = $("#productSearch");
            $(window).scroll(function () {
                if (jQuery(this).scrollTop() > 300) {
                    wrap.addClass("fix-search").fadeIn('slow');
                } else if (wrap.hasClass("fix-search")) {
                    wrap.removeClass("fix-search");
                }
            });
        });
    });
</script>

<?php
if (!empty($devicesPost)):
    if ($device['count'] <= 0): ?>
        <div class="message info empty">
            <div><?= $block->escapeHtml(__("WE'RE SORRY
            THE DEVICE IS UNAVAILABLE. PLEASE CONFIRM THE MODEL OR CONTACT OUR CUSTOMER SUPPORT")) ?></div>
        </div>
        <?php

    else:

        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $pos = $block->getPositioned();

        ?>

        <div class="category-head row map_category-spacing ">
            <div class="product-image col-12 col-md-5 col-lg-3">
                <?php if ($device['product']->getSmallImage() == 'no_selection' || !file_exists('../pub/media/catalog/product' . $device['product']->getSmallImage())) { ?>
                    <!-- Mio_logo_180X120,Mio_logo_600X400,Mio_logo_600X600 -->
                    <img class="map_productImg-mxAuto" src="<?= $mediaUrl . 'mio/images/default/Mio_logo_600X400.jpg' ?>">
                <?php } else { ?>
                    <img class="map_productImg-mxAuto"
                        src="<?= $block->getMediaUrl() . 'catalog/product' . $device['product']->getSmallImage(); ?>" />
                <?php } ?>
            </div>
            <div class="product-info col-12 col-md-7 col-lg-9 map_product-info">
                <p class="browsing"><?= __("YOU'RE BROWSING MAPS FOR"); ?></p>
                <label><?= $device['product']->getName(); ?></label>
                <p><?= $device['count'] . " " . __("Items Shown Below"); ?></p>
                <?php if ($device['product']->getLifetimeUpdates()): ?>
                    <div>
                        <p class="update-note">
                            <img src='<?= $block->getMediaUrl() . 'mio/images/maps/map-update-icon.png' ?>' />
                            <?= __('Your device comes with free maps updates, please connect your device to Navdesk to see if there is a free map update available.'); ?>
                        </p>
                    </div>
                <?php endif; ?>
            </div>
        </div>


        <div class="product-maps tab product-collateral">
            <ul class="col-xl-12 toggle-tabs">
                <?php
                foreach ($device['map'] as $value) { ?>
                    <li><a href="#" onClick="javascript:ScrollTo('<?= $value['tag'] ?>')"><?= __($value['name']) ?></a></li>
                <?php } ?>

            </ul>

        </div>
        <hr class="contentHr">

        <style>
            html,
            body {
                scroll-behavior: auto;
            }
        </style>

        <script type="text/javascript">

            function ScrollTo(id_name) {
                console.log(id_name);
                require([
                    'jquery',
                ], function ($) {
                    var aTag = $("#" + id_name);
                    $('html,body').animate({ scrollTop: aTag.offset().top - 200 }, 1000);
                });
            }
        </script>

        <?php
        foreach ($device['map'] as $_maps):
            if (!count($_maps['data'])): ?>
                <div id="<?= $_maps['tag'] ?>" class="Block_head">
                    <h2 class="map_h2Style"><?= $_maps['name'] ?></h2>
                    <hr class="contentHr">
                </div>
                <div
                    class="products wrapper map-my text-center <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
                    <?php

                    switch ($_maps['tag']) {
                        case 'tag18': //Map Update
                            echo __('There are no buyable map updates for Australia and New Zealand for your device, if you wish to purchase international maps please see below.');
                            break;
                        case 'tag73': //Subscriptions
                            echo __('All Subscriptions available for your device are included in your free Australian and New Zealand Mapping.');
                            break;
                        default:
                            echo __('There are no products available for this device.');
                            break;

                    }



                    ?>
                </div>
            <?php elseif (count($_maps['data'])): ?>
                <div id="<?= $_maps['tag'] ?>" class="Block_head">
                    <h2 class="map_h2Style"><?= $_maps['name'] ?></h2>
                    <hr class="contentHr">
                </div>
                <div class="products wrapper mapWrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
                    <ol class="products-grid slick-content">
                        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                        <?php foreach ($_maps['data'] as $_product):
                            $saleQty = $stockState->execute($_product->getSku(), 1);
                            ?>
                            <li class="item product product-item map">
                                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                                    <?php
                                    $productImage = $block->getImage($_product, $imageDisplayArea);
                                    if ($pos != null) {
                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                    }
                                    ?>
                                    <?php // Product Image ?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo"
                                        tabindex="-1">
                                        <?= $productImage->toHtml() ?>
                                    </a>
                                    <div class="product details product-item-details">
                                        <?php
                                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                        ?>
                                        <strong class="product name product-item-name">
                                            <a class="product-item-link" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                            </a>
                                        </strong>dd

                                        <div class="actions">
                                            <?php if ($showDescription): ?>
                                                <div class="product description product-item-description">
                                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                </div>
                                            <?php endif; ?>
                                            <div class="product actions" <?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                <div class="actions-primary" <?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                    <?php if ($isCartEnabled && $_product->getAddToCart()): ?>
                                                        <?php if ($_product->isAvailable() && $saleQty > 0): ?>
                                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                            <form data-role="tocart-form"
                                                                data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                                                action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                                <input type="hidden" name="product"
                                                                    value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                                <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                                    value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                    class="action button">
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span>
                                                                    <?= $block->escapeHtml(__('Out of stock')) ?>
                                                                </span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                                <a class="button btn secondary" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                                    title="<?= /* @noEscape */ $_productNameStripped ?>">

                                                    <?= $block->escapeHtml(__('Learn More')) ?>

                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ol>
                </div>
                <?php
            endif;
        endforeach;
    endif;
endif; ?>

<script>
    require([
        'jquery',
        'mio_slick'
    ], function ($) {

        $(document).ready(function () {

            var windowsize = $(window).width();
            var showItsm = (windowsize > 767) ? 3 : 1;

            $('.slick-content').not('.slick-initialized').slick({
                dots: true,
                infinite: false,
                speed: 300,
                slidesToShow: showItsm,
                adaptiveHeight: true
            });

            $('.Block_head a').click(function () {
                $('.slick-content').slick('refresh');
            });

        });

    });
</script>