<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magefan\TranslationPlus\Block\Adminhtml\Product\Translate\Index
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 */
?>
<?php
    $id = (int)$block->getProduct(0)->getId();
    $html = $block->getGroupsHtml();
?>
  <form class='form' action=<?= $block->getUrl('translationplus/product/save') ?> method='post' id='product_template_edit_form'>
<?php
    $keys = array_keys($html);
?>
<?php for ($i=0; $i < count($html[$keys[0]]); $i++) { ?>
    <table style="width:100%;">
        <thead>
            <tr>
                <?php foreach ($block->getStores() as $store) { ?>
                    <th style=" border-left: 1px solid #cccccc; " ><?= $block->escapeHtml($store->getName(). '/' .$store->getWebsite()->getName()) ?></th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                  <?php for ($j = 0; $j < count($keys); $j++) { ?>
                      <td style=" border-left: 1px solid #cccccc; padding:10px">
                          <?= $html[$keys[$j]][$i] ?>
                      </td>
                  <?php  } ?>
            </tr>
        </tbody>
    </table>
<?php } ?>
<input type='hidden' name='redirect' value=1 />
<input type='hidden' name='id' value=<?= $block->escapeHtml($id) ?> />
<input type='hidden' name='form_key' value=<?= $block->escapeHtml($block->getFormKey()) ?> />
</form>

<style>
    .translationplus-product-translate .admin__collapsible-block-wrapper.fieldset-wrapper {
        border: none;
    }

    .translationplus-product-translate  #product_template_edit_form table {
        border: 1px solid #cccccccc;
    }

    .translationplus-product-translate .use-default-label { font-size: 9px; }
    .translationplus-product-translate .use-default {padding-left: 15px;}
</style>

<?php $scriptString = <<<script
require([
    'jquery',
    'wysiwygAdapter',
    'Magento_Ui/js/modal/prompt',
    'Magento_Ui/js/modal/confirm',
    'mage/mage',
    'prototype'
], function ($, wysiwyg, prompt, confirm) {

//<![CDATA[
    $('#product_template_edit_form').mage('form').mage('validation');
    var templateControl = {

        unconvertedText: '',
        typeChange: false,
        templateName: false,
        id: 'text',

        events: {
            'click [data-role=template-save]': 'save',
            'click [data-role=template-save-and]': 'save_and',
            'click [data-role=template-back]': 'back',
        },

        init: function () {
           this.bindEvents();
        },

        bindEvents: function () {
            var events = this.events,
                eventName,
                selector,
                callback,
                key;

            for (key in events) {
                if (!events.hasOwnProperty(key)) {
                    continue;
                }

                callback    = this[events[key]];
                key         = key.split(' ');

                eventName   = key[0];
                selector    = key.slice(1).join(' ');

                $(selector).on(eventName, $.proxy(callback, this));
            }
        },

        save: function () {
            if (this.typeChange) {
                $('change_flag_element').value = '1';
            }

            // Temporary solution will be replaced after refactoring of newsletter functionality
            $('#product_template_edit_form').triggerHandler('save');
            return false;
        },
        save_and: function () {
                if (this.typeChange) {
                $('change_flag_element').value = '1';
            }
            $('input[name=redirect]').val(0);
            // Temporary solution will be replaced after refactoring of newsletter functionality
            $('#product_template_edit_form').triggerHandler('save');
            return false;
        },
         back: function () {
                window.location.href = "{$block->getUrl('catalog/product/edit', ['id' => $id])}";
            return false;
        }
    };
      $(document).ready(function(){
            $('.h1[class="page-title"]').prop("value", "NS/NR");
        });
    templateControl.init();
    templateControl.templateName = "{$block->escapeJs($block->getJsTemplateName())}";
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

