<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Sales\Block\Order\History $block */
$weSupplyHelper = $this->helper('WeSupply\Toolbox\Helper\Data');
$orderViewType = $weSupplyHelper->getOrdersViewType();
$_orders = $orderViewType !== 'ws_order_list' ? $block->getOrders() : $weSupplyHelper->getWsOrders();
$generatedOrdersLink = $orderViewType === 'ws_order_list' || $orderViewType === 'ws_order_view' ?
    $weSupplyHelper->getGenerateOrderMap($_orders, true) : false;
?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra && $orderViewType !== 'ws_order_list'): ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= /* @noEscape */ $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <?php $shippingName = $orderViewType === 'ws_order_list' ?  $_order->getShippingName() :
                            ($_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;')
                    ?>
                    <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $shippingName ?></td>
                    <?php $formattedPrice = $orderViewType === 'ws_order_list' ? $_order->getFormattedGrandTotal() : $_order->formatPrice($_order->getGrandTotal()) ?>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $formattedPrice ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= /* @escapeNotVerified */ $_order->getStatusLabel() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <?php if (is_array($generatedOrdersLink) && array_key_exists($_order->getIncrementId(),$generatedOrdersLink)): ?>
                            <?php if ($orderViewType !== 'ws_order_list'): ?>
                                <?php $printableOptions = $weSupplyHelper->generateAllPrintableOptionsForOrder($_order); ?>
                                <?php if (count($printableOptions) > 0): ?>
                                    <select class="wesupply_options" <?php echo count($printableOptions) == 1 ? 'disabled="disabled"' : ''; ?> onchange="javascript:location.href = this.value;">
                                        <?php foreach ($printableOptions as $key => $values): ?>
                                        <option value="<?= /* @escapeNotVerified */ $values['url']; ?>"><?= /* @escapeNotVerified */ __($values['label']) ?>
                                            <?php endforeach; ?>
                                    </select>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if (($orderViewType === 'ws_order_view' && $weSupplyHelper->orderViewModalEnabled()) || $orderViewType === 'ws_order_list'): ?>
                                <?php $linkHtml = $this->getLayout()
                                    ->createBlock('Magento\Framework\View\Element\Template')
                                    ->setOrderLink($generatedOrdersLink[$_order->getIncrementId()])
                                    ->setTemplate('WeSupply_Toolbox::embedded/orders/view_order_link.phtml');
                                ?>
                                <?php echo $linkHtml->toHtml(); ?>
                            <?php else: ?>
                                <a href="<?= /* @escapeNotVerified */ $generatedOrdersLink[$_order->getIncrementId()] ?>" class="action view" target="_blank">
                                    <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                                </a>
                            <?php endif; ?>
                        <?php else: ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                                <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($orderViewType !== 'ws_order_list' && $this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml() && $orderViewType !== 'ws_order_list'): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
    <?php echo $this->getChildHtml('view_order_modal'); ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.') ?></span></div>
<?php endif ?>
