<style>
  #sortable > li {
    margin: 4px;
    border: 1px #666666 solid;
    border-radius: 10px;
    display: flow-root;
    padding: 10px;
    cursor: move;
  }
  #error {
    color: red;
    text-align: center;
    font-weight: bold;
  }
  .ActionBotton {
    display: flow-root;
    margin-bottom: 50px;
    margin-right: 10px;
  }
  .ActionBotton > .queryitem {
    margin-left: 250px;
  }
  .ActionBotton > .sortsave {
    margin-left: 250px;
  }
</style>
<div class="ActionBotton">
  <button type="button" class="primary ui-button queryitem action-additional">
  	<span data-bind="text: title">Quiry to Sort</span>
  </button>
  <button type="button" class="primary ui-button sortsave action-additional">
    <span data-bind="text: title">Save</span>
  </button>
</div>
<ul id="sortable">
<?=$block->getSortItemsHTML(1, $block->getData('blockType'))?>
</ul>
<div id="error"></div>
<script>
    require(
        [
          'jquery',
          'Magento_Theme/js/sortable'
        ],
        function($)
        {
          'use strict';
          $('#back').attr('onClick', 'location.href = "<?=$block->getBackURL();?>;"');
          $('#sortable').sortable();
          $('.queryitem').on('click', function(event){
          	var id = $("select[name=stores_id]").val();
            $.ajax({
              url: "<?=$block->getItemsURL()?>",
              type: 'post',
              dataType: 'json',
              data:{
                type:'<?=$block->getData('blockType')?>',
                storeid:id
              },
              success: function(message) {
                $('#error').html(message.error);
                $('#sortable').html(message.items);
              },
              error: function(xhr,status,error) {
                $('.error').html(error);
              }
            });
          });
          $('.sortsave').on('click', function(event){
            var id = [];
            var sort = [];
            $("#sortable > li").each(function(index){
              id[index] = $(this).attr("data-id");
              sort[index] = index;
            });
            $.ajax({
              url: "<?=$block->getSaveSortURL()?>",
              type: 'post',
              dataType: 'json',
              data:{
                id:id,
                sort:sort,
                type:'<?=$block->getData('blockType')?>'
              },
              success: function(message) {
                location.replace(message.message);
              },
              error: function(xhr,status,error) {
                $('.error').html(error);
              }
            });
          });
        }
    );
</script>