
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information"></div>
        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
              <span class="title">
                <?php
                  $id = $this->getRequest()->getParam('id');
                  if (!$id) {
                    $id = 0;
                  }
                  echo $block->getImagerButton($id);
                  ?>
              </span>
            </div>
            <div class="admin__page-section-item-content">
                <?php
                  echo $block->getImagerUrl($id);
                  ?>
            </div>
        </div>
    </div>
</section>

<script>
    require(
	        [
	          'jquery'
	        ],
	        function($)
	        {
              $v = jQuery.noConflict();
              $v(document).ready(function()
              {
                  $v(".emq_zip_btn").on('click',function(e)
                  {
                      $.ajax({
                            method: "POST",
                            url: "<?php echo $block->getUrl('homepage/index/imgprocess'); ?>",
                            data: { BannersId: <?php echo $id ?>},
                            dataType: "json"
                          })
                        .done(function( msg ) {
                          if(msg.state=='success')
                          {
                              alert("Image Remove Success!!");
                              location.reload();
                          }
                          else {
                            alert("Image Remove Fail!!");
                          }
                          console.log(msg);
                      });
                  });
              });
	        }
	    );
</script>
