<?php
    $product = $block->getProduct();
    $storeCode = $block->getStoreCode();
    $baseUrl = $block->getHomeUrl();
?>

<div>

    <?php 
        $watchthevideo_link = $product->getData('watchthevideo');
    ?>

    <?php if(!empty($watchthevideo_link)): ?>
        <button class="button secondary watch_video_btn" >
            <i class="far fa-play-circle"></i>
            <span><?= __("Watch the Video") ?></span>
        </button>
        <div id="watch_video_modal" class="watch_video_modal">
            <?php if(preg_match("/youtu/i", $watchthevideo_link)): ?>
                <iframe src="<?= $block->convertVideo($watchthevideo_link) ?>" frameborder="0"></iframe>
            <?php elseif (preg_match("/youku/i", $watchthevideo_link)): ?>      
                <iframe src="https://player.youku.com/embed/<?= $block->convertVideo($watchthevideo_link); ?>" frameborder="0"></iframe>
            <?php endif; ?>
        </div>

        <script type="text/javascript">
            require([
                "jquery",
                "Magento_Ui/js/modal/modal"
            ],function($, modal) {

                var options = {
                    type: 'popup',
                    responsive: true,
                    buttons: []
                };

                var popup = modal(options, $('#watch_video_modal'));
                $(".watch_video_btn").click(function(e) {
                    $('#watch_video_modal').modal('openModal');
                });
            });
        </script>
    <?php endif; ?>

    <?php
        // 得到 buy btn link 
        $buy_btn_link = $product->getData('buyitnow');
        // 得到 buy btn flag
        $buy_btn_link_flag = $product->getData('buy_it_now_button');
    ?>
    <?php if($buy_btn_link_flag && !empty($buy_btn_link)): ?>
        <a href="
            <?php
                if (strpos($buy_btn_link, 'http') === 0) {
                    echo $buy_btn_link;
                } else {
                    echo $baseUrl.$buy_btn_link;
                }
            ?>
        " class="button btn buy_now_btn" target="_blank">
            <i class="fas fa-shopping-cart"></i>
            <?= __("Buy it Now") ?>
        </a>
    <?php endif; ?>

    <?php
        // 得到 buy btn link 
        $where_to_buy = $product->getData('wheretobuy');
        // 得到 buy btn flag
        $where_to_buy_flag = $product->getData('where_to_buy_button');

    ?>
    <?php if($where_to_buy_flag): ?>
        <a href="
           <?php
                if (empty($where_to_buy)) {
                    if ($storeCode === 'en_gb' || $storeCode === 'de_de') {
                    echo $baseUrl.'wheretobuy/online';
                    } else {
                        echo $baseUrl.'wheretobuy';
                    }
                } else {
                    if (strpos($where_to_buy, 'http') === 0) {
                        echo $where_to_buy;
                    } else {
                        echo $baseUrl.$where_to_buy;
                    }
                }
           ?>
        " class="button where_to_buy_btn" target="_blank">
        <i class="fas mgz-fa-store"></i>
           <?= __("Where to Buy") ?>
        </a>
    <?php endif; ?>
</div>