<?php

$product = $block->getProduct();
$image_base_Url  = $block->getMediaUrl();
$feature_list = array();
for ($i=1; $i<=15; $i++) { 
    $features_img = $product->getData('features_img'.$i);
    $features_title = $product->getData('features_title'.$i);
    $features_description = $product->getData('features_description'.$i);
    if(!empty($features_title) or !empty($features_description)) {
        $feature_list[] = array(
            'img' => $features_img,
            'title' =>  $features_title,
            'description' => $features_description
        );
    }
}
?>
<?php if(count($feature_list) > 0): ?>
<div class="feature-wrapper">
    <div class="box-collateral-title title">
        <h2 class="h1"><?= __("Features")?></h2>
    </div>
    <ul class="features-grid">
    <?php foreach($feature_list as $feature): ?>
                <li class="item">
                    <?php if(!empty($feature['img']) && $feature['img'] !== "no_selection"): ?>
                        <div class="thumbs">
                            <img src="<?= $image_base_Url."catalog/product".$feature['img']; ?>" alt="<?=  $feature['title'];  ?>">
                        </div>
                    <?php endif; ?>
                    <div class="desc">
                        <?php if(!empty($feature['title'])): ?>
                            <div class="title">
                                <h3><?=  $feature['title'];  ?></h3>
                            </div>
                        <?php endif; ?>
                        <?php if(!empty($feature['description'])): ?>
                            <div class="txt">
                                <p><?= $feature['description']; ?></p>
                            </div>
                        <?php endif; ?>
                    </div>
                </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>