<?php
$product = $block->getProduct();
$productName = $block->getProduct()->getName();
$Accessories = 0;
$in_the_box = $block->getInTheBox();
if(!empty($block->getCrossSellProducts()))
{
	$Accessories = count($block->getCrossSellProducts());
}

$AvailableMaps = 0;
if(!empty($block->getUpsellProducts()))
{
	$AvailableMaps = count($block->getUpsellProducts());
}

$product_video = $block->getProductVideo();

$mivue_manager_flag = $product->getMivueManager();
$mivue_app_flag 	= $product->getMivueAppYn();
$mivue_app_pro_flag = $product->getMivueAppProYn();
$mioshare_flag 		= $product->getData('mio_share');
$mionext_app_flag 	= $product->getMionextApp();
$specsName = array();
$specsName = ['Integrated safety-cams', 'Radar', 'Display', 'Video', 'Hardware', 'Software'];

$productAttributes=$product->getAttributes();

$attributesgroups=$block->getAttributeGroups($product->getAttributeSetId());

$specsAttr = $block->getGroupsAttribute($product, $productAttributes, $specsName);

?>

<ul class="toggle-tabs tab_list_pc">
	<li>
		<a href="#" onClick="javascript:ScrollTo('Overview')"><?= __('Overview') ?></a>
	</li>
	<?php if(count($product_video) > 0){
		?>
		<li>
		<a href="#" onClick="javascript:ScrollTo('Video')"><?= __('Video') ?></a>
	</li>
	<?php } ?>
	<?php if(count($specsAttr) > 0): ?>
	<li>
		<a href="#" onClick="javascript:ScrollTo('Specifications')"><?= __('Specifications') ?></a>
	</li>
	<?php endif; ?>
	<?php if($mivue_manager_flag or $mivue_app_flag or $mivue_app_pro_flag or $mioshare_flag or $mionext_app_flag): ?>
	<li>
		<a href="#" onClick="javascript:ScrollTo('Tools')"><?= __("Tools") ?></a>
	</li>
	<?php endif; ?>
	<?php if (count($in_the_box) > 0): ?>
		<li>
			<a href="#" onClick="javascript:ScrollTo('IntheBox')"><?= __("In The Box") ?></a>
		</li>
	<?php endif; ?>
	<?php if($Accessories)
	{ 
		?>
		<li><a href="#" onClick="javascript:ScrollTo('Accessories')"><?= __("Accessories") ?></a></li>
		<?php 
	}
	if($AvailableMaps)
	{ 
		?>
		<li class="last"><a href="#" onClick="javascript:ScrollTo('AvailableMaps')"><?= __("Available Maps") ?></a></li>
		<?php 
	}
	?>
</ul>
<div class='tab fixed mgz-element mgz-element-row full_width_row'>
	<div class="mgz-container inner-content ">
		<h2><?= $productName ?></h2>
			<ul class="tab_list_pc">
			<li>
				<a href="#" onClick="javascript:ScrollTo('Overview')"><?= __('Overview') ?></a>
			</li>
			<?php if(count($product_video) > 0){
				?>
				<li>
				<a href="#" onClick="javascript:ScrollTo('Video')"><?= __('Video') ?></a>
			</li>
			<?php } ?>
			<?php if(count($specsAttr) > 0): ?>
			<li>
				<a href="#" onClick="javascript:ScrollTo('Specifications')"><?= __('Specifications') ?></a>
			</li>
			<?php endif; ?>
			<?php if($mivue_manager_flag or $mivue_app_flag or $mivue_app_pro_flag or $mioshare_flag or $mionext_app_flag): ?>
			<li>
				<a href="#" onClick="javascript:ScrollTo('Tools')"><?= __("Tools") ?></a>
			</li>
			<?php endif; ?>
			<?php if (count($in_the_box) > 0): ?>
				<li>
					<a href="#" onClick="javascript:ScrollTo('IntheBox')"><?= __("In The Box") ?></a>
				</li>
			<?php endif; ?>
			<?php if($Accessories)
			{ 
				?>
				<li><a href="#" onClick="javascript:ScrollTo('Accessories')"><?= __("Accessories") ?></a></li>
				<?php 
			}
			if($AvailableMaps)
			{ 
				?>
				<li class="last"><a href="#" onClick="javascript:ScrollTo('AvailableMaps')"><?= __("Available Maps") ?></a></li>
				<?php 
			}
			?>
		</ul>
	</div>
</div>


<div class='tab_mobile closed'>
	<div class="mgz-container inner-content ">
		<div class="tab_mobile_title">
			<div class="tit">
				<h2 class="h3"><span><?= $productName ?></span></h2><i class="icon icon-down-open"></i>
			</div>
			<div class="addtocart">
				<?= $this->getLayout()->renderElement('product.info.addtocart') ?>
			</div>
		</div>
			<ul class="tab_list_mobile">
			<li>
				<a href="#" onClick="javascript:ScrollToMobile('Overview')"><?= __('Overview') ?></a>
			</li>
			<?php if(count($product_video) > 0){
				?>
				<li>
				<a href="#" onClick="javascript:ScrollToMobile('Video')"><?= __('Video') ?></a>
			</li>
			<?php } ?>
			<?php if(count($specsAttr) > 0): ?>
			<li>
				<a href="#" onClick="javascript:ScrollToMobile('Specifications')"><?= __('Specifications') ?></a>
			</li>
			<?php endif; ?>
			<?php if($mivue_manager_flag or $mivue_app_flag or $mivue_app_pro_flag or $mioshare_flag or $mionext_app_flag): ?>
			<li>
				<a href="#" onClick="javascript:ScrollToMobile('Tools')"><?= __("Tools") ?></a>
			</li>
			<?php endif; ?>
			<?php if (count($in_the_box) > 0): ?>
				<li>
					<a href="#" onClick="javascript:ScrollToMobile('IntheBox')"><?= __("In The Box") ?></a>
				</li>
			<?php endif; ?>
			<?php if($Accessories)
			{ 
				?>
				<li><a href="#" onClick="javascript:ScrollToMobile('Accessories')"><?= __("Accessories") ?></a></li>
				<?php 
			}
			if($AvailableMaps)
			{ 
				?>
				<li class="last"><a href="#" onClick="javascript:ScrollToMobile('AvailableMaps')"><?= __("Available Maps") ?></a></li>
				<?php 
			}
			?>
		</ul>
	</div>
</div>



<style>
	html,body 
	{
		scroll-behavior: smooth;
	}
</style>

<script type="text/javascript">
	function ScrollTo(id_name) 
	{
		require([
			'jquery',
			], function($) {
				var aTag = $("#"+ id_name);
				var HeaderHeight = $("#header").height()
				var tabsHeight = $(".toggle-tabs").height()
				$('html,body').animate({scrollTop: aTag.offset().top - tabsHeight - HeaderHeight},100);
			});
	}

	require([
			'jquery'
			], function($) {
			
				$(window).scroll(function() {
					
				})
			});

	require([
			'jquery'
			], function($) {
				
				$(window).scroll(function() {
					var windowsize = $(window).width();
					if (windowsize > 767) {
						var HeaderHeight = $("#header").height()
						var tabHeight = $('.toggle-tabs').offset().top + $('.toggle-tabs').height() - HeaderHeight;
							if ($(document).scrollTop() >= tabHeight) {
								$('.tab').css('top', (HeaderHeight-1) + 'px').slideDown(300)
							} else {
								$('.tab').hide()
							}
					} else {
						var HeaderHeightMobile = $("#header").height()
						var tabHeightMobile = $('#Overview').offset().top - HeaderHeightMobile - 10;
						console.log(tabHeightMobile)
						console.log($(document).scrollTop())
						if ($(document).scrollTop() >= tabHeightMobile) {
							$('.tab_mobile').css('top', (HeaderHeightMobile-1) + 'px').slideDown(300)
						} else {
							$('.tab_mobile').hide()
						}
					}
				})

				$(".tab_mobile_title h2").on('click', function(){
					var IsClosed = $('.tab_mobile').hasClass('closed')
					var HeaderHeight = $("#header").height()
					// console.log(Isopen)
					if (IsClosed) {
						$('.tab_mobile').removeClass('closed').addClass('open')
						$(".tab_list_mobile").css('top', (HeaderHeight-1) + 'px').slideDown(300)
						$(".tab_mobile_title h2 i").addClass('icon-up-open').removeClass('icon-down-open')
					} else {
						$(".tab_list_mobile").hide()
						$('.tab_mobile').removeClass('open').addClass('closed')
						$(".tab_mobile_title h2 i").addClass('icon-down-open').removeClass('icon-up-open')
					}
				})
			});

			function ScrollToMobile(id_name) {
				require([
					'jquery',
					], function($) {
							var aTag = $("#"+ id_name);
							var HeaderHeight = $("#header").height()
							var tabheight = 0
							if (id_name !== 'Overview') {
								tabheight = 64
							}
							$(".tab_list_mobile").hide()
							$('.tab_mobile').removeClass('open').addClass('closed')
							$(".tab_mobile_title h2 i").addClass('icon-down-open').removeClass('icon-up-open')
							$('html,body').animate({scrollTop: aTag.offset().top - tabheight - HeaderHeight},100);
						})
			}

</script>