<?php
/** @var \Mirasvit\Scroll\Block\Scroll $block */
if (!$block->isEnabled()) {
    return;
}
$initConfig = $block->getInitConfig();
if (!$initConfig) {
    return;
}
?>
<script type="text/x-magento-init"><?= \Mirasvit\Core\Service\SerializeService::encode($initConfig) ?></script>
<style>
    .pages, .toolbar-amount {
        display: none !important;
    }
</style>
<noscript>
    <style>
        .pages, .toolbar-amount {
            display: block !important;
        }
    </style>
</noscript>
