<?php /* @var $block Magezon\Blog\Block\Widget\PostList */?>
<?php
$title            = $block->getData('title');
$html             = $block->getPostListHtml();
$id               = 'blog-' . uniqid();
$disableBoxShadow = $block->getData('disable_box_shadow');
$disableBorder    = $block->getData('disable_border');
$disableOwlDots	  = $block->getData('owl_dots');
$padding          = ($block->getData('padding')!='') ? (int)$block->getData('padding') . 'px' : 0;
?>
<?php if ($html) { ?>
<div id="<?= $id ?>" class="blog-block">
	<?php if ($title) { ?>
		<div class="block-block-title"><h3><span><?= $title ?></span></h3></div>
	<?php } ?>
	<div class="block-block-content">
		<?= $html ?>
	</div>
	<?php if ($disableBoxShadow || $disableBorder || $padding || $disableOwlDots) { ?>
	<style>
		<?= '#'.$id ?> .block-block-content {
			<?php if ($disableBoxShadow == 1) { ?>box-shadow: none;<?php } ?>
			<?php if ($disableBorder) { ?>border: 0;<?php } ?>
			padding: <?= $padding ?>;
		}
		<?= '#'.$id ?> .block-block-content .owl-dots {
			<?php if ($disableOwlDots == 0) { ?>display: none;<?php } ?>
		}
	</style>
	<?php } ?>
</div>
<?php } ?>