<?php
/** @var \Mirasvit\LayeredNavigation\Block\Navigation\FilterExpander $block */
?>
<script type="text/x-magento-init"><?= \Mirasvit\Core\Service\SerializeService::encode([
        '.sidebar #narrow-by-list' => [
            'accordion' => [
                'multipleCollapsible' => true,
                'active'              => $block->getOpenedFilterIndexes(),
            ],
        ],
    ]) ?></script>
