<style>
.desktop-menu-account-link{
    display: none;
}
.active > .desktop-menu-account-link{
    display: block !important;
    background: #fff;
    border: solid 1px #CCCCCC;
    display: block;
    position: absolute;
    z-index: 200;
    right: 0px;
    top: 60px;
    width: 150px;
}
</style>
<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$StoreCode = $storeManager->getStore()->getCode();
$StoreId = $storeManager->getStore()->getId();

if ($StoreCode=='tw') $StoreCode = 'zh_tw';

$scopeConfig  = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface');
$disablecust = $scopeConfig->getValue('cart_setting/setting/disablecust', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $StoreId);

if ($disablecust == 0)
{
    if (!$block->isLoggedIn()) 
    {
        if ($StoreCode!='zh_tw')
        {
        ?>
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?> class="skip-account level0">
            <i class="far fa-user-circle" style='color: #999;'></i>
        </a>
        <?php
        }
        else
        {
        ?>
        <a href="https://eshop.mio.com/<?php echo $StoreCode; ?>/customer/account/login" class="skip-account level0">
            <i class="far fa-user-circle" style='color: #999;'></i>
        </a>
        <?php   
        }
    }
    else {

        $baseUrl = $block->getBaseUrl();
    ?>
    <a 
        href='#'
        class="action toggle switcher-trigger skip-account level0"
        data-mage-init='{"dropdown":{}}'>
        <i class="far fa-user-circle"></i>
        <span class="label"><?= __('Account')?></span>
        <i class="fas mgz-fa-angle-down"></i>
    </a>
    <ul id="header-account" class="dropdown switcher-dropdown item-submenu skip-account desktop-menu-account-link" data-target="dropdown">
        <li class="switcher-option">
            <a href="<?=$baseUrl.'customer/account'?>"><?= __('My Account')?></a>
        </li>
        <li class="switcher-option">
            <a href="<?=$baseUrl.'customer/account/logout'?>"><?= __('Logout')?></a>
        </li>
    </ul>

<?php
    }
}
?>