<?php
/**
    Override Magento_Checkout minicart.phtml For using Mio theme
 */
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$StoreId = $storeManager->getStore()->getStoreId();

$scopeConfig  = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface');
$enable_cart = $scopeConfig->getValue('cart_setting/setting/enablecart', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $StoreId);

$baseUrl = $storeManager->getStore()->getBaseUrl();
?>

<div data-block="minicart" class="minicart-wrapper">
    <a href="<?=$baseUrl?>worldwide/" class="skip-lang" title="Language Switch">
        <span class="glyphicon glyphicon-globe"></span>
    </a>
    <?php
    if($enable_cart==True)
    {
        ?>
        <a class="action minicart skip-link skip-cart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
        data-bind="scope: 'minicart_content'">
        <i class="fas fa-cart-arrow-down"></i>

            <span class="counter qty empty"
                data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
                <span class="counter-number count"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            </span>
        </a>
        <?php
    }
    ?>
    <?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart"
            data-role="dropdownDialog"
            data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".minicart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.minicart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>



