<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$websiteName = $storeManager->getWebsite()->getName();
$StoreCode = $storeManager->getStore()->getCode();
$StoreId = $storeManager->getStore()->getId();

if ($StoreCode=='tw') $StoreCode = 'zh_tw';

$scopeConfig  = $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface');
$disablecust = $scopeConfig->getValue('cart_setting/setting/disablecust', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $StoreId);

/*Check Login*/ 
$contextInfo = $objectManager->get('\Magento\Framework\App\Http\Context');
$customerLogin = $contextInfo->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);

/* Because of store structure, so write url here below */
$baseUrl = $storeManager->getStore()->getBaseUrl();

if(!empty($baseUrl))
{
	$ImgBaseUrl = ltrim(str_replace($StoreCode,"",$baseUrl),'/');
}

$html = $block->getMenuHtml();
$html = str_replace('data-mage-init=\'{"ninjamenus"', 'data-mage-init=\'{"ninjamenustop"', $block->getMenuHtml());

$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<?php if($html) 
{ 
    ?>
    <nav class="navigation" data-action="navigation">

        <!-- Login/Register -->
        <?php 
        if ($disablecust == 0)
        {
            if(!$customerLogin):
                if($StoreCode!='zh_tw')
                {
                ?>
                <div class="nav-item level0" id="mio-account">
                    <a href="<?=$baseUrl.'customer/account'?>">
                        <i class="item-icon mio far fa-user-circle"></i>
                        <?= __('Login/Register');?>
                    </a>
                </div>
                <?php
                }
                else
                {
                ?>
                <div class="nav-item level0" id="mio-account">
                    <a href="https://eshop.mio.com/<?php echo $StoreCode; ?>/customer/account/login">
                        <i class="item-icon mio far fa-user-circle"></i>
                        <?= __('Login/Register');?>
                    </a>
                </div>
                <?php
                }
            else: ?>
            <div class="nav-item level0" id="mio-account">
                <div class="actions dropdown options switcher-options">
                    <a 
                    href='#'
                    class="action toggle switcher-trigger"
                    data-mage-init='{"dropdown":{}}'
                    data-toggle="dropdown"
                    data-trigger-keypress-button="true">
                    <i class="item-icon mio far fa-user-circle"></i>
                    <?= __('Account');?>
                    <span class="opener"></span>
                    </a>
                    <ul class="dropdown switcher-dropdown item-submenu" data-target="dropdown">
                        <li class="switcher-option">
                            <a href="<?=$baseUrl.'customer/account'?>"><?= __('My Account')?></a>
                        </li>
                        <li class="switcher-option">
                            <a href="<?=$baseUrl.'customer/account/logout'?>"><?= __('Logout')?></a>
                        </li>
                    </ul>
                </div>
            </div>
            <?php
            endif;
        }
        ?>

        <!--Navigation Menu -->
        <?= $html ?>
        <div class="nav-item level0 lang_switcher">
            <a href="<?=$baseUrl.'worldwide/'?>">
                <img src="<?php echo $mediaUrl.'wysiwyg/flags/'.$StoreCode.'.png'; ?>" alt="<?=$websiteName;?>" title="<?=$websiteName;?>">
                <?=$websiteName;?>
            </a>
        </div>
    </nav>

    <script type="text/javascript">
        require([
            'jquery'
            ], function ($) {
                var scrolled = false;
                $(window).scroll(function(){

                    if($(window).width()>=768){
                        if(160<$(window).scrollTop() && !scrolled){

                            $('#header').addClass("sticky-header");
                            scrolled = true;

                        }
                        if(160>=$(window).scrollTop() && scrolled){
                            $('#header').removeClass("sticky-header");
                            scrolled = false;

                        }
                    }
                });
            });
    </script>
    <?php 
} 
?>