<div class="mstInPage__item magento_catalog_product">
    <!-- ko if: (imageUrl && $parents[2].config.isShowImage) -->
    <div class="mst__product-image">
        <a rel="noreferrer" data-bind="attr: {href: url}">
            <img data-bind="attr: {src: imageUrl}"/>
        </a>
    </div>
    <!-- /ko -->

    <div class="mst__product-meta">
        <a rel="noreferrer" class="mst__title" data-bind="html: name, attr: {href: url}, highlight"></a>

        <!-- ko if: (sku && $parents[2].config.isShowSku) -->
        <div class="mst__sku" data-bind="text: sku, highlight"></div>
        <!-- /ko -->

        <!-- ko if: (description && $parents[2].config.isShowDescription) -->
        <div class="mst__description" data-bind="text: description, highlight"></div>
        <!-- /ko -->

        <!-- ko if: (rating && $parents[2].config.isShowRating) -->
        <div class="mst__rating">
                <div class="rating-summary">
                    <div class="rating-result">
                        <span data-bind="style: { width: rating + '%' }"></span>
                    </div>
                </div>
        </div>
        <!-- /ko -->

        <div class="mst__product-cart">
            <!-- ko if: (addToCartUrl && $parents[2].config.isShowCartButton) -->
            <div class="to-cart">
                <a class="action primary mst__add_to_cart" data-bind="attr: { _href: addToCartUrl }">
                    <span><?= __('Add To Cart') ?></span>
                </a>
            </div>
            <!-- /ko -->

            <div class="store">
                <div data-bind="html: price" class="price"></div>
            </div>
        </div>
    </div>
</div>
