<?php 
$overview_youtube 	 = $block->getProduct()->getOverviewYoutube();
$youtubeUrl 		 = $block->convertYoutube($overview_youtube);
$overview_image 	 = $block->getProduct()->getOverviewImage();
$overview_image_Url  = $block->getMediaUrl()."catalog/product".$overview_image;
?>
<div class="visual-box">
	<div id="player">
		<div class="video" style="background-image:url('<?=$overview_image_Url?>')">
			<div class="embed-responsive embed-responsive-16by9">
				<iframe width="420" height="315" src="<?=$youtubeUrl?>"></iframe>
			</div>
		</div>
	</div>
</div>