<?php
$productId = $block->getProduct()->getId();
$ProductDevices = $block->getProductCustomRelated($productId);
?>

<div class="compatibility-list">
	<h2><?=__('Compatibility List')?></h2>
	<ul class="compList">
		<?php
		if(!empty($ProductDevices))
		{
			foreach($ProductDevices as $ProductName=>$ProductUrl)
			{
				//商品可以瀏覽
				if(!empty($ProductUrl))
				{
					?>
					<li class="item">
						<a href="<?php echo $ProductUrl; ?>" title="<?php echo $ProductName; ?>">
							<h3 class="product-name"><?=$ProductName?></h3>
						</a>
					</li>
					<?php 
				}
				else
				{
					//商品已經無法瀏覽
					?>
					<li class="item">
						<h3 class="product-name"><font color="#bbb"><?=$ProductName?></font></h3>
					</li>
					<?php
				}
			} 
		}
		?>
	</ul>
</div>